import{test}from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import vm from'node:vm';import{canonicalHash}from'../scripts/lib/mc.mjs';import{renderReport,buildMetadata}from'../scripts/make-report.mjs';import{reportContext}from'../scripts/lib/report-context.mjs';
const study={author_name:'Nagihan Şirin',institution:'Örnek Üniversitesi',department:'Orman Fakültesi',advisor:'Prof. Dr. Örnek Danışman',project_name:'Kent Ağaçları Projesi',title:'Kent Ağaçlarının Karbon Stoku',purpose:'Kent parkında ölçülen ağaçların envanterinin ve karbon stokunun belirlenmesi.',orcid:'0000-0002-1825-0097'};
test('yayın künyesinde temel bibliyografik alanlar zorunlu; kurum ve danışman isteğe bağlıdır',()=>{assert.equal(reportContext.validate(study).valid,true);assert.equal(reportContext.validate({...study,institution:'',advisor:''}).valid,true);assert.equal(reportContext.validate({...study,institution:'',advisor:'',study_type:'Lisans bitirme çalışması'}).valid,true);assert.equal(reportContext.orcidValid('0000-0002-1825-0098'),false);assert.ok(reportContext.validate({}).errors.project_name);assert.throws(()=>reportContext.decode(JSON.stringify({schema:'dendrogeo-report-context/1',study})),/onayı eksik/);assert.equal(reportContext.decode('eski istek notu'),null);const v=reportContext.decode(JSON.stringify({schema:'dendrogeo-report-context/1',study,publication_consent:true}));assert.equal(v.advisor,study.advisor);assert.ok(!('role' in reportContext.clean({...study,role:'owner'})));});
test('rapor başlığı, danışman, proje ve kurum tüm yayın alanlarına aktarılır; sayısal ölçümler korunur',()=>{const snap=JSON.parse(readFileSync(new URL('./fixtures/report-snapshot.json',import.meta.url)));snap.study={...study,title:'Araştırma <script>alert(1)</script>'};snap.author.name=study.author_name;const before=JSON.stringify(snap.totals),h=renderReport(snap,{id:'DGR-2026-0021',hash:canonicalHash(snap)}),md=buildMetadata(snap,{id:'DGR-2026-0021',hash:canonicalHash(snap)});assert.ok(h.includes('Araştırma &lt;script&gt;'));assert.ok(!h.includes('<h1>Araştırma <script>'));assert.ok(h.includes(study.project_name));assert.ok(h.includes(study.advisor));assert.equal(md.study.institution,study.institution);assert.ok(md.contributors.some(x=>x.contributorType==='Supervisor'&&x.name===study.advisor));assert.equal(md.creators[0].affiliation[0].name,study.institution);assert.equal(JSON.stringify(snap.totals),before);});
test('vazgeçilen künye ve eşzamanlı tıklama yayın isteği oluşturmaz',async()=>{const ctx=vm.createContext({USER:{id:'u'},PROJ_LIST:[],console,Set,Map});ctx.globalThis=ctx;vm.runInContext(readFileSync(new URL('../src/services/academic-profile.js',import.meta.url),'utf8'),ctx);let posts=0,resolve;ctx.dgPubInsertRequest=async()=>{posts++;return{ok:true}};ctx.dgReportQuestions=()=>new Promise(r=>resolve=r);const pending=ctx.dgReportCollectRequest(25,true);await ctx.dgReportCollectRequest(25,true);resolve(null);await pending;assert.equal(posts,0);ctx.dgReportQuestions=async()=>({schema:'dendrogeo-report-context/1',study});await ctx.dgReportCollectRequest(25,true);assert.equal(posts,1);});
test('kuyruk işlenmiş eski taleplerle dolu olsa da yeni isteğe sayfalayarak ulaşır',async()=>{
 const{fetchPending}=await import('../scripts/publish-queue.mjs');const original=globalThis.fetch,seen=[];globalThis.fetch=async url=>{const u=new URL(url),offset=Number(u.searchParams.get('offset'));seen.push(offset);assert.ok(u.searchParams.get('created_at').startsWith('gte.2026-10-04'));return{status:200,ok:true,json:async()=>offset===0?Array.from({length:50},(_,i)=>({id:'old'+i})):[{id:'fresh'}]};};try{const rows=await fetchPending(1,Array.from({length:50},(_,i)=>'old'+i),'2026-10-04T00:00:00Z');assert.deepEqual(rows.map(r=>r.id),['fresh']);assert.deepEqual(seen,[0,50]);}finally{globalThis.fetch=original;}
});
test('ORCID URL and compact identifier normalize before profile validation',()=>{for(const value of ['https://orcid.org/0000-0002-1825-0097','0000000218250097']){const result=reportContext.clean({...study,orcid:value});assert.equal(result.orcid,study.orcid);assert.equal(reportContext.validate(result).valid,true);}});
