import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
function env(fetch){const c=vm.createContext({fetch,AbortController,Map,Date,Math,URLSearchParams,console:{warn(){}},setTimeout:(fn,ms)=>setTimeout(fn,ms<3000?0:ms),clearTimeout});vm.runInContext(readFileSync(new URL('../src/services/lc-stac.js',import.meta.url),'utf8'),c);return c;}
test('504 then 429 recover under a finite attempt budget',async()=>{let calls=0;const c=env(async()=>++calls<3?new Response('',{status:calls===1?504:429,headers:{'Retry-After':'3600'}}):Response.json({real:true}));const out=await vm.runInContext('dgLcFetchJson("https://test")',c);assert.equal(out.real,true);assert.equal(calls,3);});
test('permanent 403 and invalid JSON are never retried',async()=>{for(const response of [()=>new Response('',{status:403}),()=>new Response('invalid')]){let calls=0;const c=env(async()=>{calls++;return response();});await assert.rejects(vm.runInContext('dgLcFetchJson("https://test")',c));assert.equal(calls,1);}});
test('offline failures stop after three attempts',async()=>{let calls=0;const c=env(async()=>{calls++;throw new TypeError('offline');});await assert.rejects(vm.runInContext('dgLcFetchJson("https://test")',c),/offline/);assert.equal(calls,3);});
test('a transient COG range transport failure retries and returns the real byte range',async()=>{let client,calls=0;class Response{constructor(response,done){this.response=response;this.done=done;}get ok(){return this.response.ok;}get status(){return this.response.status;}getHeader(k){return this.response.headers.get(k);}async getData(){try{return await this.response.arrayBuffer();}finally{this.done();}}}class Client{constructor(url){this.url=url;}}const c=env(async()=>{if(++calls===1)throw new TypeError('temporary connection reset');return{ok:true,status:206,headers:new Map([['Content-Range','bytes 0-1/2']]),arrayBuffer:async()=>new Uint8Array([1,2]).buffer};});c.GeoTIFF={BaseClient:Client,BaseResponse:Response,fromCustomClient:x=>{client=x;return x;},fromUrl:()=>null};await vm.runInContext('dgLcOpenRaster("https://test/tile.tif")',c);const response=await client.request({headers:{Range:'bytes=0-1'}});assert.equal(calls,2);assert.equal(response.status,206);assert.equal(response.getHeader('Content-Range'),'bytes 0-1/2');assert.deepEqual([...new Uint8Array(await response.getData())],[1,2]);});
test('parent cancellation is not retried or swallowed by SAS fallback',async()=>{let calls=0;const c=env(async()=>{calls++;throw Error('must not fetch');});c.signal=AbortSignal.abort();vm.runInContext('var DG_LC_SAS="https://test/"',c);await assert.rejects(vm.runInContext('dgLcGetSas("a",signal)',c),{name:'AbortError'});assert.equal(calls,0);});
test('SAS cache is collection scoped and expires before token expiry',async()=>{let calls=0;const c=env(async()=>{calls++;return Response.json({token:'se='+encodeURIComponent(new Date(Date.now()+600000).toISOString())});});vm.runInContext('var DG_LC_SAS="https://test/"',c);await vm.runInContext('dgLcGetSas("a")',c);await vm.runInContext('dgLcGetSas("a")',c);await vm.runInContext('dgLcGetSas("b")',c);assert.equal(calls,2);vm.runInContext('DG_LC_SAS_CACHE.get("a").expires=Date.now()+1000',c);await vm.runInContext('dgLcGetSas("a")',c);assert.equal(calls,3);});
