import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
function env(fetch){const c=vm.createContext({fetch,AbortController,Map,Date,Math,URLSearchParams,console:{warn(){}},setTimeout:(fn,ms)=>setTimeout(fn,ms<3000?0:ms),clearTimeout});vm.runInContext(readFileSync(new URL('../src/services/lc-stac.js',import.meta.url),'utf8'),c);return c;}
test('504 then 429 recover under a finite attempt budget',async()=>{let calls=0;const c=env(async()=>++calls<3?new Response('',{status:calls===1?504:429,headers:{'Retry-After':'3600'}}):Response.json({real:true}));const out=await vm.runInContext('dgLcFetchJson("https://test")',c);assert.equal(out.real,true);assert.equal(calls,3);});
test('permanent 403 and invalid JSON are never retried',async()=>{for(const response of [()=>new Response('',{status:403}),()=>new Response('invalid')]){let calls=0;const c=env(async()=>{calls++;return response();});await assert.rejects(vm.runInContext('dgLcFetchJson("https://test")',c));assert.equal(calls,1);}});
test('offline failures stop after three attempts',async()=>{let calls=0;const c=env(async()=>{calls++;throw new TypeError('offline');});await assert.rejects(vm.runInContext('dgLcFetchJson("https://test")',c),/offline/);assert.equal(calls,3);});
test('parent cancellation is not retried or swallowed by SAS fallback',async()=>{let calls=0;const c=env(async()=>{calls++;throw Error('must not fetch');});c.signal=AbortSignal.abort();vm.runInContext('var DG_LC_SAS="https://test/"',c);await assert.rejects(vm.runInContext('dgLcGetSas("a",signal)',c),{name:'AbortError'});assert.equal(calls,0);});
test('SAS cache is collection scoped and expires before token expiry',async()=>{let calls=0;const c=env(async()=>{calls++;return Response.json({token:'se='+encodeURIComponent(new Date(Date.now()+600000).toISOString())});});vm.runInContext('var DG_LC_SAS="https://test/"',c);await vm.runInContext('dgLcGetSas("a")',c);await vm.runInContext('dgLcGetSas("a")',c);await vm.runInContext('dgLcGetSas("b")',c);assert.equal(calls,2);vm.runInContext('DG_LC_SAS_CACHE.get("a").expires=Date.now()+1000',c);await vm.runInContext('dgLcGetSas("a")',c);assert.equal(calls,3);});
