import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const c=vm.createContext({window:{}});vm.runInContext(readFileSync(new URL('../src/ui/grid-build-controller.js',import.meta.url),'utf8'),c);
const create=c.window.DG_GRID_BUILD_CONTROLLER_UI.create;
function setup(overrides={}){const button={isConnected:true,disabled:false,textContent:'🔲 Grid Oluştur'},accepted=[],messages=[];let epochs=0;const run=create({getPark:()=>[[[39,32]]],getOptions:()=>({size:20,clearance:5}),nextEpoch:()=>++epochs,getButton:()=>button,build:async()=>({status:'ready'}),accept:(...x)=>accepted.push(x),notify:(...x)=>messages.push(x),...overrides});return{run,button,accepted,messages,epochs:()=>epochs};}
test('concurrent clicks produce one job; completion releases lock for the next job',async()=>{let release,jobs=0;const x=setup({build:()=>{jobs++;return new Promise(r=>release=r);}});const first=x.run();assert.equal(x.button.disabled,true);await x.run();assert.equal(jobs,1);assert.equal(x.epochs(),1);release({status:'ready'});await first;assert.equal(x.button.disabled,false);assert.equal(x.accepted.length,1);const second=x.run();assert.equal(jobs,2);release({status:'ready'});await second;});
test('stale result is not accepted and resets the connected button',async()=>{const x=setup({build:async()=>({status:'stale'})});await x.run();assert.equal(x.accepted.length,0);assert.equal(x.button.disabled,false);assert.equal(x.button.textContent,'🔲 Grid Oluştur');assert.equal(x.messages.length,0);});
test('build and accept failures notify and release the lock',async()=>{for(const override of [{build:async()=>{throw Error('build failed');}},{accept:()=>{throw Error('render failed');}}]){const x=setup(override);await x.run();await x.run();assert.equal(x.messages.length,2);assert.equal(x.button.disabled,false);assert.equal(x.epochs(),2);}});
test('no park stops before options and epoch; detached button is not rewritten on completion',async()=>{const missing=setup({getPark:()=>null,getOptions:()=>assert.fail('options read')});await missing.run();assert.deepEqual(missing.messages,[['Önce park seç','warn']]);assert.equal(missing.epochs(),0);const detached=setup();detached.button.isConnected=false;await detached.run();assert.equal(detached.button.disabled,true);assert.equal(detached.accepted.length,1);});
