import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const c=vm.createContext({window:{}});vm.runInContext(readFileSync(new URL('../src/ui/grid-waypoint-controller.js',import.meta.url),'utf8'),c);
function setup(overrides={}){const source={},park=[],cells=[{id:1}],messages=[],completed=[],requests=[];const run=c.window.DG_GRID_WAYPOINT_CONTROLLER_UI.create({getContext:()=>({source,park}),resolveReadiness:(mode,s)=>{assert.equal(s,source);assert.equal(mode,'manual');return{ok:true,projectId:7,targetCells:cells};},create:async r=>{requests.push(r);return{status:'created'};},complete:(...args)=>completed.push(args),translate:s=>'T:'+s,notify:(...args)=>messages.push(args),...overrides});return{run,source,park,cells,messages,completed,requests};}
test('every preflight failure stops before creation and completion',async()=>{const cases={'grid-missing':'Önce grid oluştur','project-missing':'Önce proje seç','manual-selection-missing':'Önce hücre seçin','target-cells-missing':'Uygun hücre yok','surface-stale':'T:Yüzey değişti. Waypoint üretmeden önce gridi yeniden oluşturun.'};for(const [reason,message] of Object.entries(cases)){const x=setup({resolveReadiness:()=>({ok:false,reason})});await x.run('manual');assert.equal(x.requests.length,0);assert.equal(x.completed.length,0);assert.deepEqual(x.messages,[reason==='surface-stale'?[message,'warn']:[message]]);}});
test('cancelled, stale and failed writes never complete',async()=>{for(const status of ['cancelled','stale','write-failed']){const x=setup({create:async()=>({status,error:{message:'offline'}})});await x.run('manual');assert.equal(x.completed.length,0);assert.equal(x.messages.length,status==='cancelled'?0:1);if(status==='write-failed')assert.deepEqual(x.messages,[['Hata: offline','err']]);}});
test('successful creation receives original context and completes with the selected project',async()=>{const x=setup();await x.run('manual');assert.equal(x.requests[0].source,x.source);assert.equal(x.requests[0].park,x.park);assert.equal(x.requests[0].targetCells,x.cells);assert.equal(x.requests[0].projectId,7);assert.equal(x.completed[0][1],7);assert.equal(x.messages.length,0);});
test('unexpected creation errors propagate without completing or inventing a result',async()=>{const x=setup({create:async()=>{throw Error('read failed');}});await assert.rejects(x.run('manual'),/read failed/);assert.equal(x.completed.length,0);assert.equal(x.messages.length,0);});
