import{test}from'node:test';import assert from'node:assert/strict';import vm from'node:vm';import{readFileSync}from'node:fs';
const src=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
function client(fetch){const ctx=vm.createContext({fetch,AbortController,Date,Map,console:{log(){}},setTimeout:(f,ms)=>setTimeout(f,ms/100),clearTimeout,localStorage:{getItem(){return null},setItem(){}}});vm.runInContext(src('src/services/osm-client.js'),ctx);return{ctx,run:s=>vm.runInContext(s,ctx)};}
test('a slow first mirror is hedged, loser is cancelled and successful result is cached',async()=>{let requests=0,cancelled=0;const a=client((url,{signal})=>{requests++;if(url.includes('lz4'))return new Promise((_,reject)=>signal.addEventListener('abort',()=>{cancelled++;reject(Object.assign(Error('aborted'),{name:'AbortError'}));}));return Promise.resolve({ok:true,json:async()=>({elements:[{id:1}]})});});const data=await a.run('overpassRequest("query","park")');assert.equal(data.elements.length,1);assert.equal(requests,2);assert.equal(cancelled,1);await a.run('overpassRequest("query","park")');assert.equal(requests,2);assert.equal(a.run('OVERPASS_HEALTH.get(OVERPASS_URLS[0])?.badUntil||0'),0);});
test('identical concurrent requests share the pending operation',async()=>{let requests=0,release;const a=client(()=>{requests++;return new Promise(r=>release=r);});const first=a.run('overpassRequest("same query")'),second=a.run('overpassRequest("same  query")');assert.equal(first,second);assert.equal(requests,1);release({ok:true,json:async()=>({elements:[]})});await first;assert.equal(requests,1);});
test('partial Overpass results are rejected; quarantined mirrors are not retried',async()=>{let requests=0;const a=client(async()=>{requests++;return{ok:true,json:async()=>requests===1?{elements:[{id:99}],remark:'runtime error: timeout'}:{elements:[{id:2}]}};});assert.equal((await a.run('overpassRequest("query")')).elements[0].id,2);a.run('for(const url of OVERPASS_URLS)OVERPASS_HEALTH.set(url,{badUntil:Date.now()+60000})');const before=requests;assert.equal(await a.run('overpassRequest("different")'),null);assert.equal(requests,before);});
function landcover(){let requests=0;const ctx=vm.createContext({window:{},Date,Map,Number,AbortSignal,overpassRequest:async()=>{requests++;return ctx.data;}});vm.runInContext(src('src/services/lc-osm.js'),ctx);ctx.bbox={minLat:39,minLon:32,maxLat:40,maxLon:33};ctx.data={elements:[{type:'way',tags:{natural:'water'},geometry:[{lat:39.2,lon:32.2},{lat:39.3,lon:32.2},{lat:39.3,lon:32.3},{lat:39.2,lon:32.2}]},{type:'way',tags:{highway:'service',surface:'asphalt',width:'4'},geometry:[{lat:39.5,lon:32.4},{lat:39.6,lon:32.4}]},{type:'way',tags:{building:'yes'},geometry:[{lat:39.7,lon:32.7},{lat:39.8,lon:32.7},{lat:39.8,lon:32.8}]}]};return{ctx,run:s=>vm.runInContext(s,ctx),requests:()=>requests};}
test('fresh park coverage supplies water and road evidence with no repeat request',async()=>{const a=landcover();a.ctx.window.DG_SURFACE_OSM={...a.ctx.data,bbox:a.ctx.bbox,fetchedAt:new Date().toISOString()};const water=await a.run('dgLcFetchWaterPolygons(bbox)'),roads=await a.run('dgLcFetchRoadFeatures(bbox)');assert.equal(a.requests(),0);assert.equal(water.length,1);assert.equal(roads.length,1);assert.equal(roads[0].surface,'asphalt');});
test('missing coverage uses one combined water-road query and stale coverage is not reused',async()=>{const a=landcover();a.ctx.window.DG_SURFACE_OSM={elements:[],bbox:a.ctx.bbox,fetchedAt:new Date(Date.now()-700000).toISOString()};const [water,roads]=await Promise.all([a.run('dgLcFetchWaterPolygons(bbox)'),a.run('dgLcFetchRoadFeatures(bbox)')]);assert.equal(a.requests(),1);assert.equal(water.length,1);assert.equal(roads.length,1);});
test('a late coverage response cannot overwrite a newly selected park',async()=>{let release;const ctx=vm.createContext({window:{},PARK_POLY:[[[39,32],[39,33],[40,33]]],IMP_RINGS:[],IMP_LINES:[],GRID_BLOCK_LINES:[],WATER_RINGS:[],WATER_LINES:[],overpassRequest:()=>new Promise(r=>release=r),console});vm.runInContext(src('src/services/park-query.js'),ctx);const request=vm.runInContext('queryDetailedCoverage()',ctx);ctx.PARK_POLY=[[[41,34],[41,35],[42,35]]];release({elements:[]});assert.equal(await request,false);assert.equal(ctx.window.DG_SURFACE_OSM,null);});
