import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const src=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
function env(extra={}){const c=vm.createContext({window:{},PARK_HOLES:[],console:{warn(){},log(){}},URLSearchParams,AbortController,Map,Date,setTimeout,clearTimeout,...extra});vm.runInContext(src('src/domain/parks/area.js'),c);vm.runInContext(src('src/domain/parks/segment-intersection.js'),c);vm.runInContext(src('src/domain/parks/point-in-polygon.js'),c);vm.runInContext(src('src/domain/parks/bounds.js'),c);vm.runInContext(src('src/services/park-geometry.js'),c);vm.runInContext(src('src/application/parks/find-park-candidates.js'),c);vm.runInContext(src('src/application/parks/fetch-detailed-coverage.js'),c);vm.runInContext(src('src/application/parks/classify-coverage-elements.js'),c);vm.runInContext(src('src/application/parks/find-nominatim-boundary.js'),c);vm.runInContext(src('src/adapters/parks/nominatim-client.js'),c);vm.runInContext(src('src/services/park-query.js'),c);return {c,run:s=>vm.runInContext(s,c)};}
const polygon={osm_type:'way',osm_id:123,name:'Test Park',geojson:{type:'Polygon',coordinates:[[[32,39],[32.01,39],[32.01,39.01],[32,39.01],[32,39]],[[32.004,39.004],[32.006,39.004],[32.006,39.006],[32.004,39.006],[32.004,39.004]]]}};
const search=[{osm_type:'way',osm_id:123,category:'leisure',type:'park',boundingbox:['39','39.01','32','32.01']}];
test('unavailable Overpass recovers an actual OSM polygon, preserves holes and caches it',async()=>{let requests=0;const a=env({overpassRequest:async()=>null,fetch:async(url)=>{requests++;return{ok:true,json:async()=>url.includes('/search')?search:[polygon]};}});const found=await a.run('queryPark(39.002,32.002)');assert.equal(found[0].id,123);assert.equal(found[0].rings.inner.length,1);assert.equal(found[0].rings.outer[0][0][0],39);assert.ok(found[0].area>0);await a.run('queryPark(39.003,32.003)');assert.equal(requests,2);assert.equal(a.run('pointInPark(39.005,32.005,DG_PARK_BOUNDARY_CACHE.get("way/123").park.rings)'),false);});
test('both boundary services unavailable throw an error instead of an empty park result',async()=>{const a=env({overpassRequest:async()=>null,fetch:async()=>{throw Error('offline');}});await assert.rejects(a.run('queryPark(39,32)'),/offline/);});
test('a complete empty Overpass response remains a genuine no-match result',async()=>{let fetched=false;const a=env({overpassRequest:async()=>({elements:[]}),fetch:()=>{fetched=true;}});assert.equal((await a.run('queryPark(39,32)')).length,0);assert.equal(fetched,false);});
test('Nominatim bounding boxes and points are never used as park polygons',async()=>{const a=env({fetch:async(url)=>({ok:true,json:async()=>url.includes('/search')?search:[{...polygon,geojson:{type:'Point',coordinates:[32.002,39.002]}}]})});assert.equal((await a.run('dgParkBoundaryFallback(39.002,32.002,1200)')).length,0);});
test('an unrelated lookup object or polygon outside the selected point is rejected',async()=>{const a=env({fetch:async(url)=>({ok:true,json:async()=>url.includes('/search')?search:[{...polygon,osm_id:456},polygon]})});assert.equal((await a.run('dgParkBoundaryFallback(39.005,32.005,1200)')).length,0);});
function registry(query){const calls={manual:0,draw:0,toasts:[]};const c=vm.createContext({window:{},navigator:{onLine:true},console:{warn(){}},toast:(...x)=>calls.toasts.push(x),queryPark:query,DG_PARK:{id:7},DG_PARK_CAND:{name:'Existing'},DG_PARK_ANCHOR:null,DG_MANUAL_PENDING:null,PARK_CANDS:[]});for(const p of ['src/domain/parks/identity.js','src/adapters/parks/park-store.js','src/application/parks/register-park.js','src/adapters/parks/project-store.js','src/application/parks/create-project.js','src/adapters/parks/project-link-store.js','src/application/parks/link-project.js','src/application/parks/detect-park.js','src/application/parks/create-manual-park.js','src/adapters/parks/park-search.js','src/application/parks/search-park-by-name.js','src/services/park-registry.js'])vm.runInContext(src(p),c);c.dgOfferManualPark=()=>calls.manual++;c.drawPark=async()=>calls.draw++;return{c,calls,run:s=>vm.runInContext(s,c)};}
test('a park lookup failure preserves the existing park and never opens manual drawing',async()=>{const a=registry(async()=>{throw Error('HTTP 504');});await a.run('dgDetectAt(39,32)');assert.equal(a.calls.manual,0);assert.equal(a.c.DG_PARK.id,7);assert.ok(a.calls.toasts.some(x=>x[0].includes('bağlantısı başarısız')));});
test('a late empty result from an earlier click cannot replace a newly found park',async()=>{let release,n=0;const a=registry(()=>++n===1?new Promise(r=>release=r):Promise.resolve([{id:9}]));const old=a.run('dgDetectAt(39,32)');await a.run('dgDetectAt(40,33)');release([]);await old;assert.equal(a.calls.draw,1);assert.equal(a.calls.manual,0);});
test('a late detailed coverage response cannot replace the selected park evidence',async()=>{let release;const a=env({PARK_POLY:[[[39,32],[39,33],[40,33]]],IMP_RINGS:[],IMP_LINES:[],GRID_BLOCK_LINES:[],WATER_RINGS:[],WATER_LINES:[],overpassRequest:()=>new Promise(r=>release=r)});const old=a.run('queryDetailedCoverage()');a.c.PARK_POLY=[[[40,33],[40,34],[41,34]]];release({elements:[]});assert.equal(await old,false);assert.equal(a.c.window.DG_SURFACE_OSM,null);});
test('concurrent detailed coverage calls share one complete Overpass request',async()=>{let calls=0,release;const a=env({PARK_POLY:[[[39,32],[39,33],[40,33]]],IMP_RINGS:[],IMP_LINES:[],GRID_BLOCK_LINES:[],WATER_RINGS:[],WATER_LINES:[],overpassRequest:()=>{calls++;return new Promise(r=>release=r);}});const first=a.run('queryDetailedCoverage()'),second=a.run('queryDetailedCoverage()');assert.equal(first,second);assert.equal(calls,1);release({elements:[]});assert.equal(await first,true);});
test('park detection is independent of a blocked detailed Overpass request and rejects partial responses',async()=>{let count=0;const c=vm.createContext({fetch:async(_u,{body})=>{if(decodeURIComponent(body).includes('surface'))return new Promise(()=>{});count++;return{ok:true,status:200,json:async()=>count===1?{elements:[{id:99}],remark:'runtime timeout'}:{elements:[{id:1}]}};},AbortController,setTimeout:(f,ms)=>{const t=setTimeout(f,ms);t.unref();return t;},clearTimeout,console:{warn(){},log(){}},Date,Map});vm.runInContext(src('src/services/osm-client.js'),c);vm.runInContext('overpassRequest("surface","yüzey+su")',c);const first=vm.runInContext('overpassRequest("park","park")',c),second=vm.runInContext('overpassRequest("park","park")',c);assert.equal(first,second);assert.equal((await first).elements[0].id,1);assert.equal(count,2);});
