import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const c=vm.createContext({window:{}});vm.runInContext(readFileSync(new URL('../src/ui/park-mode-controller.js',import.meta.url),'utf8'),c);
function setup({initial=false,map={},elements=true}={}){let mode=initial;const events=[],messages=[],classes=new Set(['blue']),attrs={};const button={classList:{toggle:(k,on)=>on?classes.add(k):classes.delete(k),add:k=>classes.add(k)},setAttribute:(k,v)=>attrs[k]=v},hint={};const run=c.window.DG_PARK_MODE_CONTROLLER_UI.create({getMode:()=>mode,setMode:v=>{mode=v;events.push('mode:'+v);},getButton:()=>elements?button:null,getHint:()=>elements?hint:null,bindClick:()=>events.push('bind'),clearCandidates:()=>events.push('candidates'),clear:()=>events.push('clear'),getMap:()=>map,notify:(...a)=>messages.push(a)});return{run,mode:()=>mode,events,messages,button,hint,classes,attrs};}
test('opening updates accessible button and hint before reporting ready mode',()=>{const x=setup();x.run();assert.equal(x.mode(),true);assert.equal(x.attrs['aria-pressed'],'true');assert.equal(x.classes.has('blue'),false);assert.equal(x.button.textContent,'🌳 Park Analizi Modu: AÇIK');assert.equal(x.hint.textContent,'Şimdi haritada parkın içine tıkla.');assert.deepEqual(x.events,['mode:true','bind']);assert.equal(x.messages.length,1);});
test('closing binds then clears candidates and park without success notification',()=>{const x=setup({initial:true});x.run();assert.equal(x.mode(),false);assert.deepEqual(x.events,['mode:false','bind','candidates','clear']);assert.equal(x.attrs['aria-pressed'],'false');assert.equal(x.classes.has('blue'),true);assert.equal(x.messages.length,0);});
test('missing map restores closed mode and retry hint without clearing park',()=>{const x=setup({map:null});x.run();assert.equal(x.mode(),false);assert.equal(x.attrs['aria-pressed'],'false');assert.equal(x.button.textContent,'🌳 Park Analizi Modu: KAPALI');assert.equal(x.hint.textContent,'Harita henüz hazır değil; tekrar deneyin.');assert.deepEqual(x.events,['mode:true','bind','mode:false']);assert.equal(x.messages.length,0);});
test('missing presentation elements do not prevent mode opening or closing',()=>{const x=setup({elements:false});x.run();assert.equal(x.mode(),true);x.run();assert.equal(x.mode(),false);assert.deepEqual(x.events.slice(-3),['bind','candidates','clear']);});
