import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
function env(){const c=vm.createContext({window:{},console,Date,URLSearchParams,Set,Map});vm.runInContext(readFileSync(new URL('../src/services/lc-s2.js',import.meta.url),'utf8'),c);return c;}
const scene=(date,cloud=0,tile='A')=>({cloud,it:{properties:{datetime:date+'T10:00:00Z','s2:mgrs_tile':tile}}});
test('season selection keeps early and late evidence instead of clustering in September',()=>{const c=env();c.items=['2021-09-29','2021-09-25','2021-09-20','2021-06-05'].map(d=>scene(d));const r=vm.runInContext('dgS2SelectScenes(items,2)',c);assert.equal(r.length,2);assert.deepEqual(new Set(r.map(x=>x.it.properties.datetime.slice(0,10))),new Set(['2021-09-29','2021-06-05']));});
test('a second intersecting tile gets coverage before additional dates on the first',()=>{const c=env();c.items=[scene('2021-09-29',0),scene('2021-06-05',0),scene('2021-09-25',5,'B')];const r=vm.runInContext('dgS2SelectScenes(items,2)',c);assert.deepEqual(new Set(r.map(x=>x.it.properties['s2:mgrs_tile'])),new Set(['A','B']));});
test('missing or invalid UTM CRS cannot silently use Ankara coordinates',()=>{const c=env();for(const code of [0,4326,32661,32700]){c.image={getGeoKeys:()=>({ProjectedCSTypeGeoKey:code})};assert.throws(()=>vm.runInContext('dgS2AssetEpsg(image)',c),/koordinat sistemi/);}for(const code of [32601,32660,32701,32760]){c.image={getGeoKeys:()=>({ProjectedCSTypeGeoKey:code})};assert.equal(vm.runInContext('dgS2AssetEpsg(image)',c),code);}});
test('one outlier date cannot establish seasonal vegetation or water',()=>{const c=env();c.values=[.1,.12,.95];assert.equal(vm.runInContext('dgS2ConfirmedExtreme(values)',c),.12);c.values=[.8];assert.equal(vm.runInContext('dgS2ConfirmedExtreme(values)',c),null);});
test('relative vegetation profile uses median NDVI and counts distinct acquisition days',()=>{const c=env();c.evidence={ndvi:[.2,.4,.6,.8],dates:new Set(['2021-06-01','2021-06-01','2021-08-15'])};assert.deepEqual(JSON.parse(JSON.stringify(vm.runInContext('dgS2VegetationSummary(evidence)',c))),{ndviMedianYear:.5,ndviObs:2});});
test('new confirmed evidence takes precedence while legacy profiles remain readable',()=>{const c=vm.createContext({window:{},console});vm.runInContext(readFileSync(new URL('../src/services/lc-validate.js',import.meta.url),'utf8'),c);c.p={obs:5,ndvi:.1,mndwi:-.28,ndbi:.084,ndviMaxYear:.9,ndviConfirmedYear:.12};assert.equal(vm.runInContext('dgValSpectralPredict(p)',c),'hard');delete c.p.ndviConfirmedYear;assert.equal(vm.runInContext('dgValSpectralPredict(p)',c),'green');});
