import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import {webcrypto} from 'node:crypto';import polygonClipping from 'polygon-clipping';
const source=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
function app(){const elements=new Map();const el=id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',style:{},value:'',querySelectorAll:()=>[]});return elements.get(id);};const ctx=vm.createContext({window:{polygonClipping},crypto:webcrypto,TextEncoder,URLSearchParams,Date,setTimeout,clearTimeout,console,document:{getElementById:el},esc:String,dgCf:s=>s,toast:(...a)=>ctx.messages.push(a),messages:[],USER:{id:'user-a'},DG_PARK:{id:7,name:'Park'},DG_PARK_SESSION:new Map(),PARK_POLY:[],PARK_HOLES:[],map:{removeLayer(){},closePopup(){}},sb:{}});for(const p of ['src/core/surface-display.js','src/services/lc-config.js','src/services/lc-geo.js','src/services/lc-validate.js','src/services/lc-s2.js','src/services/lc-review.js','src/ui/lc-sens.js'])vm.runInContext(source(p),ctx);const run=s=>vm.runInContext(s,ctx);run('DG_SENS.record=dgSensNewRecord()');return{ctx,run,el};}
function fixture(a,holes=false){const {ctx,run}=a;const epsg=32631;const xy=(x,y)=>{const p=run(`dgLcUtmInverse(${500000+x},${1000+y},${epsg})`);return[p.lon,p.lat];};const ring=(x0,y0,x1,y1)=>[xy(x0,y0),xy(x1,y0),xy(x1,y1),xy(x0,y1)];const outer=ring(0,0,20,10).map(p=>[p[1],p[0]]),hole=ring(1,1,3,3).map(p=>[p[1],p[0]]);ctx.PARK_POLY=[outer];ctx.PARK_HOLES=holes?[hole]:[];const park=run('dgSurfacePark(PARK_POLY,PARK_HOLES,32631)');ctx.park=park;const cells=[0,1].map(i=>({row:0,col:i,epsg,classKey:'green',areaM2:holes&&i===0?96:100,quadWgs:ring(i*10,0,(i+1)*10,10),center:{lat:xy(i*10+5,5)[1],lon:xy(i*10+5,5)[0]}}));ctx.cells=cells;ctx.geoms={};for(const c of cells)ctx.geoms['0:'+c.col]=ctx.window.DG_SURFACE_REVIEW.cell(c,park,epsg);run('DG_LC_LAST={result:{cells,groupAreas:{green:cells.reduce((n,c)=>n+c.areaM2,0),water:0,hard:0,bare:0,other:0}},report:{year:2021}};DG_SENS.geometry=geoms;DG_SENS.parkGeometry=park;DG_SENS.epsg=32631');return{ring,cells,park};}
test('fractional boundaries and overlaps conserve area; newest boundary takes precedence',()=>{const a=app(),f=fixture(a);a.ctx.features=[{type:'building',ring:f.ring(2,2,8,8)},{type:'pool',ring:f.ring(5,5,9,9)}];const result=a.run('dgSurfaceSummarize({green:200},cells,c=>c.classKey,geoms,features,32631,park)');assert.ok(Math.abs(result.building-27)<.001);assert.ok(Math.abs(result.pool-16)<.001);assert.ok(Math.abs(Object.values(result).reduce((s,v)=>s+v,0)-200)<.001);assert.equal(f.cells[0].classKey,'green');});
test('park holes and outside geometry are excluded from reviewed building area',()=>{const a=app(),f=fixture(a,true);a.ctx.features=[{type:'building',ring:f.ring(-20,-20,30,30)}];const r=a.run('dgSurfaceSummarize({green:196},cells,c=>c.classKey,geoms,features,32631,park)');assert.ok(Math.abs(r.building-196)<.001);assert.ok(Math.abs(r.green)<.001);});
test('self-crossing boundaries are rejected',()=>{const a=app();assert.equal(a.ctx.window.DG_SURFACE_REVIEW.validRing([[0,0],[1,1],[0,1],[1,0]]),false);assert.equal(a.ctx.window.DG_SURFACE_REVIEW.validRing([[0,0],[1,0],[1,1],[0,1]]),true);});
test('geometry fingerprint changes when the boundary or source classes change',async()=>{const a=app(),f=fixture(a);const R=a.ctx.window.DG_SURFACE_REVIEW;const first=await R.fingerprint(f.cells,a.ctx.PARK_POLY,[],{year:2021});assert.match(first,/^[a-f0-9]{64}$/);assert.equal(first,await R.fingerprint(f.cells,a.ctx.PARK_POLY,[],{year:2021}));const changed=structuredClone(f.cells);changed[0].classKey='water';assert.notEqual(first,await R.fingerprint(changed,a.ctx.PARK_POLY,[],{year:2021}));});
test('zero sensitivity stays zero and starts an unsaved preview',()=>{const a=app();a.run('dgSensSlide("hard",0)');assert.equal(a.run('DG_SENS.record.sens.hard'),0);assert.equal(a.run('DG_SENS.editing'),true);assert.equal(a.run('DG_SENS.record.draftDirty'),true);a.run('clearTimeout(DG_SENS.debounce)');});
test('saved spectral decisions are frozen until editing; visual decisions remain protected',()=>{const a=app();fixture(a);a.run('DG_SENS.record.corrections={"0:0":{from:"green",to:"water",method:"sensitivity"}};DG_SENS.editing=false');assert.equal(a.run('dgSensEffective(cells[0])'),'water');a.run('DG_SENS.editing=true');assert.equal(a.run('dgSensEffective(cells[0])'),'green');a.run('DG_SENS.record.corrections["0:0"].method="visual-cell"');assert.equal(a.run('dgSensEffective(cells[0])'),'water');});
test('inadequate or edge spectral evidence preserves the original class',()=>{const a=app();fixture(a);a.run('DG_SENS.record.profile={cells:{"0:0":{obs:1,ndvi:-.2,mndwi:.8,ndbi:-.4}}}');assert.equal(a.run('dgSensEffective(cells[0])'),'green');a.run('cells[0].areaM2=30;DG_SENS.record.profile.cells["0:0"].obs=5');assert.equal(a.run('dgSensEffective(cells[0])'),'green');});
test('PB04 offset and STAC scale-offset yield equivalent reflectance',()=>{const a=app();const fn=a.ctx.dgS2Reflectance;assert.equal(fn(3000,{properties:{'s2:processing_baseline':'05.11'}},'B04'),.2);assert.equal(fn(2000,{properties:{'s2:processing_baseline':'03.00'}},'B04'),.2);assert.ok(Math.abs(fn(3000,{assets:{B04:{'raster:bands':[{scale:.0001,offset:-.1}]}}},'B04')-.2)<1e-9);assert.equal(fn(0,{},'B04'),null);});
test('latest acquisitions use a rolling window ending today without future dates',()=>{const a=app();const range=a.ctx.dgS2SeasonRange(2021,'latest');assert.ok(Date.parse(range.end)<=Date.now());assert.ok(Math.abs((Date.parse(range.end)-Date.parse(range.start))/86400000-120)<1e-6);assert.match(range.label,/güncel/);});
test('account save uses revision compare-and-swap and reports conflicts',async()=>{const a=app();let filters=[];const q={eq:(k,v)=>{filters.push([k,v]);return q;},select:()=>q,maybeSingle:async()=>({data:null,error:null})};a.ctx.sb={from:()=>({update:()=>q})};await assert.rejects(()=>a.ctx.window.DG_SURFACE_REVIEW.save({owner:'u',parkId:7,fingerprint:'f'},4),/başka cihaz/);assert.ok(filters.some(([k,v])=>k==='revision'&&v===4));});
test('failed account save retains draft and never announces saved success',async()=>{const a=app();fixture(a);a.run('DG_SENS.record.features=[{type:"building",ring:cells[0].quadWgs}];dgSensRender=()=>{};dgSensRefreshLayer=()=>{}');a.ctx.window.DG_SURFACE_REVIEW.save=async()=>{throw Error('offline');};a.ctx.window.DG_LC_VALIDATE.saveCampaign=async()=>true;await a.run('dgSensAccept()');assert.equal(a.run('DG_SENS.record.acceptedAt'),undefined);assert.match(a.run('DG_SENS.status'),/Hesaba kaydedilemedi/);assert.equal(a.ctx.messages.at(-1)[1],'err');});
test('successful account save snapshots areas and freezes the accepted layer',async()=>{const a=app();fixture(a);a.run('DG_SENS.record.fingerprint="f";DG_SENS.record.features=[{type:"building",ring:cells[0].quadWgs}];dgSensRender=()=>{};dgSensRefreshLayer=()=>{}');a.ctx.window.DG_SURFACE_REVIEW.save=async()=>3;a.ctx.window.DG_LC_VALIDATE.saveCampaign=async()=>true;await a.run('dgSensAccept()');assert.equal(a.run('DG_SENS.revision'),3);assert.equal(a.run('DG_SENS.editing'),false);assert.equal(a.run('DG_SENS.record.draftDirty'),false);assert.ok(Math.abs(a.run('DG_SENS.record.acceptedAreas.building')-100)<.001);});
test('increasing hard sensitivity expands the preview without altering baseline hectares',()=>{const a=app();fixture(a);a.run('DG_SENS.record.profile={cells:{"0:0":{obs:5,ndvi:.25,mndwi:-.15,ndbi:-.1}}};DG_SENS.record.sens.hard=0');assert.equal(a.run('dgSensEffective(cells[0])'),'green');a.run('DG_SENS.record.sens.hard=100');assert.equal(a.run('dgSensEffective(cells[0])'),'hard');assert.ok(Math.abs(a.run('dgSensAreas().hard')-100)<.001);assert.equal(a.run('DG_LC_LAST.result.groupAreas.green'),200);});
test('active park identity comes from DG_PARK, never the session cache Map',()=>{const a=app();assert.equal(a.run('dgSensParkId().id'),7);a.ctx.DG_PARK=null;assert.equal(a.run('dgSensParkId().id'),null);});
test('building cell correction remains a separate class and enters the accepted publication geometry',async()=>{const a=app();fixture(a);a.run('DG_SENS.record.fingerprint="f";DG_SENS.record.corrections={"0:0":{from:"green",to:"building",method:"visual-cell"}};dgSensRender=()=>{};dgSensRefreshLayer=()=>{}');a.ctx.window.DG_SURFACE_REVIEW.save=async()=>1;a.ctx.window.DG_LC_VALIDATE.saveCampaign=async()=>true;await a.run('dgSensAccept()');const snap=a.run('DG_SENS.record.acceptedResult');assert.equal(snap.areas.building,100);assert.equal(snap.areas.hard,0);assert.equal(snap.features.find(f=>f.properties.class==='building').properties.area_m2,100);});
test('OSM building footprint and pool stay independent, manual boundary overrides exact overlap',()=>{const a=app(),f=fixture(a);const way=(id,tags,ring)=>({type:'way',id,tags,geometry:[...ring,ring[0]].map(p=>({lon:p[0],lat:p[1]}))});const objs=a.ctx.dgSurfaceObjects([way(1,{building:'yes'},f.ring(0,0,10,10)),way(2,{leisure:'swimming_pool'},f.ring(10,0,20,10))],32631);a.ctx.objects=objs;a.run('DG_SENS.record.objectFeatures=objects');let area=a.run('dgSensAreas()');assert.ok(Math.abs(area.building-100)<.001);assert.ok(Math.abs(area.pool-100)<.001);assert.equal(area.hard,0);a.ctx.manual={type:'green',ring:f.ring(0,0,5,10)};a.run('DG_SENS.record.features=[manual]');area=a.run('dgSensAreas()');assert.ok(Math.abs(area.building-50)<.001);assert.ok(Math.abs(area.green-50)<.001);});
test('raw raster class prevents whole-cell road refinements spilling beyond exact vector boundary',()=>{const a=app();fixture(a);a.run('cells[0].classKey="hard";cells[0].rasterClassKey="green"');assert.equal(a.run('dgSensEffective(cells[0])'),'green');});
test('published surface snapshot rejects inconsistent area totals and other park identities',async()=>{const {reviewedSurface}=await import('../scripts/surface-report.mjs');const a=app();fixture(a);const snap=await a.run('dgSensResultSnapshot({...DG_SENS.record,acceptedAt:new Date().toISOString(),acceptedAreas:dgSensAreas()})');assert.equal(reviewedSurface(snap,7).classes.find(c=>c.key==='green').ha,.02);assert.throws(()=>reviewedSurface(snap,8),/kimliği/);const bad=structuredClone(snap);bad.areas.green=500;assert.throws(()=>reviewedSurface(bad,7),/uyuşmuyor/);});
test('slider changes reuse partitions without clipping and geometry edits invalidate the cache',()=>{const a=app(),f=fixture(a);a.ctx.features=[{type:'building',ring:f.ring(2,2,8,8)}];const first=a.run('dgSurfaceResolved(cells,c=>"green",geoms,features,32631,park)');const pc=a.ctx.window.polygonClipping;const original=pc.intersection;let calls=0;pc.intersection=(...args)=>{calls++;return original(...args);};try{const second=a.run('dgSurfaceResolved(cells,c=>"hard",geoms,features,32631,park)');assert.equal(calls,0);assert.equal(second[0].geom,first[0].geom);assert.ok(second.some(p=>p.type==='hard'));a.ctx.features.push({type:'pool',ring:f.ring(11,1,14,4)});const third=a.run('dgSurfaceResolved(cells,c=>"hard",geoms,features,32631,park)');assert.ok(calls>0);assert.ok(third.some(p=>p.type==='pool'));}finally{pc.intersection=original;}});
test('closing a park during snapshot preparation prevents its remote save',async()=>{const a=app();fixture(a);a.run('DG_SENS.record.features=[{type:"building",ring:cells[0].quadWgs}];dgSensRender=()=>{};dgSensRefreshLayer=()=>{};dgSensResultSnapshot=async()=>{DG_SENS.epoch++;return {}}');let saves=0;a.ctx.window.DG_SURFACE_REVIEW.save=async()=>{saves++;};await a.run('dgSensAccept()');assert.equal(saves,0);});
test('incomplete raster coverage cannot be saved as a complete publication map',async()=>{const a=app();fixture(a);a.run('DG_LC_LAST.result.groupAreas.green=300;DG_SENS.record.features=[{type:"building",ring:cells[0].quadWgs}];dgSensRender=()=>{};dgSensRefreshLayer=()=>{}');let saves=0;a.ctx.window.DG_SURFACE_REVIEW.save=async()=>{saves++;};await a.run('dgSensAccept()');assert.equal(saves,0);assert.match(a.run('DG_SENS.status'),/tüm parkı kapsamıyor/);});
test('plastic pier footprints override water completely without turning nearby water into hard surface',()=>{const a=app(),f=fixture(a);a.ctx.objects=[{type:'way',id:1,tags:{natural:'water'},geometry:[...f.ring(0,0,20,10),f.ring(0,0,20,10)[0]].map(p=>({lon:p[0],lat:p[1]}))},{type:'way',id:2,tags:{man_made:'pier',material:'plastic'},geometry:[...f.ring(2,2,8,8),f.ring(2,2,8,8)[0]].map(p=>({lon:p[0],lat:p[1]}))}];const out=a.run('dgSurfaceObjects(objects,32631)');a.ctx.features=out;const areas=a.run('dgSurfaceSummarize({green:200},cells,c=>c.classKey,geoms,features,32631,park)');assert.ok(Math.abs(areas.hard-36)<.001);assert.ok(Math.abs(areas.water-164)<.001);});
test('linear piers use an explicit width; unknown widths are not invented',()=>{const a=app(),f=fixture(a);const pts=[f.ring(2,2,2,2)[0],f.ring(8,2,2,2)[0]].map(p=>({lon:p[0],lat:p[1]}));a.ctx.objects=[{type:'way',id:1,tags:{man_made:'pier',width:'2'},geometry:pts},{type:'way',id:2,tags:{man_made:'pier'},geometry:pts}];assert.equal(a.run('dgSurfaceObjects(objects,32631).length'),1);});
test('live report follows edits while retaining original raster in a separate disclosure',()=>{const a=app();fixture(a);a.el('landCoverReport').innerHTML='original baseline';a.run('dgSensUpdateSummary()');assert.match(a.el('landCoverReport').innerHTML,/Güncel yüzey önizlemesi/);a.run('DG_SENS.record.corrections={"0:0":{to:"building",method:"visual-cell"}};dgSensUpdateSummary()');assert.match(a.el('landCoverReport').innerHTML,/Bina.*0.010 ha/);assert.match(a.el('landCoverReport').innerHTML,/original baseline/);assert.equal((a.el('landCoverReport').innerHTML.match(/<details>/g)||[]).length,1);});
test('opacity extremes and display corner rounding preserve analytic geometry and areas',()=>{const a=app();fixture(a);const before=a.run('JSON.stringify(dgSensAreas())');a.run('dgSensOpacity(0)');assert.equal(a.run('DG_SENS.opacity'),0);a.run('dgSensOpacity(100)');assert.equal(a.run('DG_SENS.opacity'),100);const softened=a.run('dgSensSoftRing([...cells[0].quadWgs,cells[0].quadWgs[0]],32631)');assert.ok(softened.length>5);assert.equal(a.run('JSON.stringify(dgSensAreas())'),before);});
test('natural display changes raster stairs while preserving a measured building footprint and all analytic totals',()=>{
 const a=app();const shift=r=>r.map(p=>[p[0]+500000,p[1]+1000]);const c=shift([[40,0],[40,8],[48,8],[48,16],[56,16],[56,24],[64,24],[64,32],[72,32],[72,40],[80,40],[80,100]]),park=[[shift([[0,0],[100,0],[100,100],[0,100],[0,0]])]],building=[[shift([[10,10],[25,10],[25,25],[10,25],[10,10]])]],green=[[[[500000,1000],...c,[500000,1100],[500000,1000]]]],hard=[[[...c,[500100,1100],[500100,1000],c[0]]]];
 const g=polygonClipping.difference(green,building);a.ctx.visualPark=park;a.ctx.visualParts=[{type:'green',method:'review-cell',geom:g,areaM2:1},{type:'hard',method:'review-cell',geom:hard,areaM2:2},{type:'building',method:'osm-boundary',geom:building,areaM2:225}];const before=JSON.stringify(a.ctx.visualParts);const exact=a.run('dgSurfaceMergeSync(visualParts,32631)');a.ctx.exact=exact;const visual=a.run('dgSurfaceDisplaySync(visualParts,32631,visualPark,exact)');assert.equal(JSON.stringify(a.ctx.visualParts),before);assert.notDeepEqual(JSON.parse(JSON.stringify(visual)),JSON.parse(JSON.stringify(exact)));assert.deepEqual(JSON.parse(JSON.stringify(visual.find(f=>f.properties.class==='building').geometry)),JSON.parse(JSON.stringify(exact.find(f=>f.properties.class==='building').geometry)));assert.deepEqual(visual.map(f=>f.properties.area_m2),exact.map(f=>f.properties.area_m2));
});
