import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import pc from 'polygon-clipping';
function engine(){const ctx=vm.createContext({window:{polygonClipping:pc},setTimeout,console});for(const f of ['src/services/lc-geo.js','src/contracts/surface-review.js','src/adapters/surface/review-store.js','src/domain/surface/review-geometry.js','src/adapters/surface/osm-review-objects.js','src/adapters/surface/review-worker.js','src/services/lc-review.js'])vm.runInContext(readFileSync(new URL('../'+f,import.meta.url),'utf8'),ctx);return {ctx,run:s=>vm.runInContext(s,ctx)};}
const origin=[500000,4420000],rect=(x,y,w,h)=>[[[origin[0]+x,origin[1]+y],[origin[0]+x+w,origin[1]+y],[origin[0]+x+w,origin[1]+y+h],[origin[0]+x,origin[1]+y+h],[origin[0]+x,origin[1]+y]]];
function input(a,green,park=rect(0,0,80,60),clearance=3){a.ctx.green=green;a.ctx.park=park;const outer=a.run('dgSurfaceUnproject([park],32636)[0].map(r=>r.map(p=>[p[1],p[0]]))');return {size:20,clearance,epsg:32636,outer,holes:[],greenOnly:true,parts:[{type:'green',geom:green}],blockRings:[],blockLines:[]};}
test('partial green cells survive while rounded waypoint positions avoid water, hard ground and park edges',async()=>{const a=engine(),park=rect(0,0,73,57),green=pc.difference([park],[rect(28,0,8,57)],[rect(48,18,15,17)]),d=input(a,green,park);a.ctx.d=d;const r=await a.run('dgSurfaceGrid(d)');assert.ok(r.cells.length>0);assert.ok(r.cells.some(c=>c.areaM2<300),'partial cells must survive');for(const c of r.cells){a.ctx.p=[c.lon,c.lat];a.ctx.f={geometry:c.geometry};const xy=a.run('dgSurfaceProject([p],32636)[0]');a.ctx.xy=xy;assert.ok(a.run('dgGridPointDistance(xy,green)')>=3,'point inside green with >=3m margin');const geom=a.run('dgSurfaceFeatureGeometry(f,32636)');assert.ok(a.run('dgGridPointDistance(xy,dgSurfaceFeatureGeometry(f,32636))')>=0);assert.ok(pc.difference(geom,green).length===0,'cell drawing is clipped to green');}});
test('every disconnected usable green island within one grid cell gets its own point',async()=>{const a=engine(),green=[rect(1,1,8,18),rect(11,1,8,18)],d=input(a,green,rect(0,0,20,20),1);a.ctx.d=d;const r=await a.run('dgSurfaceGrid(d)');assert.equal(r.cells.length,2);assert.notEqual(r.cells[0].id,r.cells[1].id);for(const island of green){a.ctx.island=[island];assert.ok(r.cells.some(c=>{a.ctx.p=[c.lon,c.lat];return a.run('dgGridPointDistance(dgSurfaceProject([p],32636)[0],island)>0');}));}});
test('park holes are never sampled and boundary safety can be adjusted',async()=>{const a=engine(),hole=rect(28,18,20,20),d=input(a,[rect(0,0,80,60)]);a.ctx.hole=hole;d.holes=a.run('dgSurfaceUnproject([hole],32636)[0].map(r=>r.map(p=>[p[1],p[0]]))');a.ctx.d=d;const r=await a.run('dgSurfaceGrid(d)');for(const c of r.cells){a.ctx.p=[c.lon,c.lat];assert.ok(a.run('dgGridPointDistance(dgSurfaceProject([p],32636)[0],[hole])')<=-3);}d.clearance=8;const farther=await a.run('dgSurfaceGrid(d)');assert.ok(farther.areaM2<r.areaM2);assert.ok(farther.cells.every(c=>c.clearanceM>=8));});
test('narrow unsafe corridors yield no points rather than moving waypoints onto roads',async()=>{const a=engine(),d=input(a,[rect(0,0,80,5)]);a.ctx.d=d;assert.equal((await a.run('dgSurfaceGrid(d)')).cells.length,0);});
test('explicit linear road widths also exclude nearby green sampling points',async()=>{const a=engine(),d=input(a,[rect(0,0,80,60)]);a.ctx.line=[[500000,4420030],[500080,4420030]];const pts=a.run('line.map(p=>{const q=dgLcUtmInverse(p[0],p[1],32636);return[q.lat,q.lon]})');d.blockLines=[{pts,w:2}];a.ctx.d=d;const r=await a.run('dgSurfaceGrid(d)');for(const c of r.cells){a.ctx.p=[c.lon,c.lat];const xy=a.run('dgSurfaceProject([p],32636)[0]');assert.ok(Math.abs(xy[1]-4420030)>=5);}});
test('an unclassified park cannot silently produce a green-only sampling grid',async()=>{const a=engine(),d=input(a,[]);a.ctx.d=d;await assert.rejects(()=>a.run('dgSurfaceGrid(d)'),/Yeşil alan bulunamadı/);});
test('millimetre precision survives nearly identical UTM edges during repeated grid erosion',async()=>{const a=engine();const x=469725.058999998,y=4426706.308;const r=(dx,dy,w,h)=>[[[x+dx,y+dy],[x+dx+w,y+dy],[x+dx+w,y+dy+h],[x+dx,y+dy+h],[x+dx,y+dy]]];a.ctx.park=r(0,0,120,100);const outer=a.run('dgSurfaceUnproject([park],32636)[0].map(r=>r.map(p=>[p[1],p[0]]))');const parts=[];for(let row=0;row<10;row++)for(let col=0;col<12;col++){const poly=r(col*10+(col%2?1.8e-9:0),row*10,10,10);parts.push({type:'green',geom:[poly]});}a.ctx.d={size:20,clearance:3,epsg:32636,outer,holes:[],greenOnly:true,parts,blockRings:[],blockLines:[]};const result=await a.run('dgSurfaceGrid(d)');assert.ok(result.cells.length>20);assert.ok(result.cells.every(c=>Number.isFinite(c.lat)&&Number.isFinite(c.lon)&&c.clearanceM>=3));});
