import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const src=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
function ctx(extra={}){return vm.createContext({window:{},Date,Map,AbortController,AbortSignal,URLSearchParams,console:{log(){},warn(){}},setTimeout,clearTimeout,...extra});}
const bbox={minLat:39,minLon:32,maxLat:40,maxLon:33};const data={elements:[{type:'way',tags:{natural:'water'},geometry:[{lat:39.2,lon:32.2},{lat:39.3,lon:32.2},{lat:39.3,lon:32.3},{lat:39.2,lon:32.2}]},{type:'way',tags:{building:'yes'},geometry:[{lat:39.2,lon:32.2},{lat:39.3,lon:32.2},{lat:39.3,lon:32.3}]},{type:'way',tags:{highway:'service',surface:'asphalt',width:'4'},geometry:[{lat:39.4,lon:32.4},{lat:39.5,lon:32.5}]}]};
test('water and road evidence share one bounded request; building polygons are not water',async()=>{let calls=0;const c=ctx({fetch:async()=>{calls++;return{ok:true,json:async()=>data};}});vm.runInContext(src('src/services/lc-osm.js'),c);c.bbox=bbox;const [water,road]=await Promise.all([vm.runInContext('dgLcFetchWaterPolygons(bbox)',c),vm.runInContext('dgLcFetchRoadFeatures(bbox)',c)]);assert.equal(calls,1);assert.equal(water.length,1);assert.equal(road.length,1);});
test('fresh complete park coverage is reused without any additional request',async()=>{let calls=0;const c=ctx({overpassRequest:async()=>{calls++;return data;}});c.window.DG_SURFACE_OSM={...data,bbox,fetchedAt:new Date().toISOString()};vm.runInContext(src('src/services/lc-osm.js'),c);c.bbox=bbox;await Promise.all([vm.runInContext('dgLcFetchWaterPolygons(bbox)',c),vm.runInContext('dgLcFetchRoadFeatures(bbox)',c)]);assert.equal(calls,0);});
test('analysis waits for its pending detailed coverage and does not repeat a failed request',async()=>{let calls=0,release;const park=[[[39,32],[40,33]]],c=ctx({PARK_POLY:park,overpassRequest:async()=>{calls++;return data;}});c.window.DG_SURFACE_OSM_PENDING={boundary:JSON.stringify(park),promise:new Promise(r=>release=r)};vm.runInContext(src('src/services/lc-osm.js'),c);c.bbox=bbox;const job=vm.runInContext('dgLcOsmData(bbox)',c);release(false);assert.equal(await job,null);assert.equal(calls,0);});
test('other parks and expired coverage are not reused',async()=>{let calls=0;const c=ctx({overpassRequest:async()=>{calls++;return data;}});c.window.DG_SURFACE_OSM={...data,bbox:{...bbox,maxLon:32.5},fetchedAt:new Date().toISOString()};vm.runInContext(src('src/services/lc-osm.js'),c);c.bbox=bbox;await vm.runInContext('dgLcOsmData(bbox)',c);assert.equal(calls,1);});
test('the total detailed Overpass budget stops mirror rotation, even on repeated 504 errors',async()=>{let calls=0,time=0;class Clock extends Date{static now(){return time;}}const c=ctx({Date:Clock,fetch:async()=>{calls++;time+=10000;return{ok:false,status:504,text:async()=>''};}});vm.runInContext(src('src/services/osm-client.js'),c);assert.equal(await vm.runInContext('overpassRequest("detail","yüzey+su")',c),null);assert.equal(calls,2);});
test('a stalled STAC request is aborted and rejects instead of returning fabricated data',async()=>{const c=ctx({setTimeout:(f,ms)=>setTimeout(f,ms/1000),fetch:(_u,{signal})=>new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(Object.assign(Error('aborted'),{name:'AbortError'}))))});vm.runInContext(src('src/services/lc-stac.js'),c);await assert.rejects(vm.runInContext('dgLcFetchJson("https://example.test")',c),/aborted/);});
test('range client preserves byte-range headers and keeps the timeout through response-body reads',async()=>{let client,seen;const c=ctx({setTimeout:(f,ms)=>setTimeout(f,ms/1000),GeoTIFF:{BaseClient:class{constructor(url){this.url=url;}},BaseResponse:class{},fromCustomClient:x=>{client=x;return Promise.resolve(x);}},fetch:async(_url,{headers,signal})=>{seen=headers;return{ok:true,status:206,headers:new Map([['Content-Range','bytes 0-10/100']]),arrayBuffer:()=>new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(Error('body aborted'))))};}});vm.runInContext(src('src/services/lc-stac.js'),c);await vm.runInContext('dgLcOpenRaster("https://example.test/cog.tif")',c);const r=await client.request({headers:{Range:'bytes=0-10'}});assert.equal(seen.Range,'bytes=0-10');assert.equal(r.status,206);assert.equal(r.getHeader('Content-Range'),'bytes 0-10/100');await assert.rejects(r.getData(),/body aborted/);});
test('a source-wide timeout cancels a stalled directory/range stage and cannot publish partial tiles',async()=>{let signal;const c=ctx({setTimeout:(f,ms)=>setTimeout(f,ms/1000)});vm.runInContext(src('src/services/lc-engine.js'),c);Object.assign(c,{DG_LC_MAX_TILES:12,dgLcFindTiles:async()=>[{id:'tile',assets:{map:{href:'https://example.test'}}}],dgLcGetSas:async()=>'',dgLcGetDataAsset:x=>x.assets.map,dgLcSignedHref:x=>x,dgLcProcessTile:(_i,_h,_g,_s,s)=>{signal=s;return new Promise((_,reject)=>s.addEventListener('abort',()=>reject(Error('abort'))));}});await assert.rejects(vm.runInContext('dgLcAnalyzeSource({label:"Primary"},{},{})',c),/zaman aşımı/);assert.equal(signal.aborted,true);});
