import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import {webcrypto} from 'node:crypto';import polygonClipping from 'polygon-clipping';
const source=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
function app(){const elements=new Map();const el=id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',style:{},value:'',querySelectorAll:()=>[]});return elements.get(id);};const ctx=vm.createContext({window:{polygonClipping},crypto:webcrypto,TextEncoder,URLSearchParams,Date,setTimeout,clearTimeout,console,document:{getElementById:el,querySelectorAll:()=>[]},esc:String,dgCf:s=>s,toast:(...a)=>ctx.messages.push(a),messages:[],USER:{id:'user-a'},DG_PARK:{id:7,name:'Park'},DG_PARK_SESSION:new Map(),PARK_POLY:[],PARK_HOLES:[],map:{removeLayer(){},closePopup(){}},sb:{}});for(const p of ['src/core/surface-display.js','src/services/lc-config.js','src/services/lc-geo.js','src/services/lc-validate.js','src/services/lc-s2.js','src/services/lc-review.js','src/ui/lc-sens.js'])vm.runInContext(source(p),ctx);const run=s=>vm.runInContext(s,ctx);run('DG_SENS.record=dgSensNewRecord()');return{ctx,run,el};}
function fixture(a,holes=false){const {ctx,run}=a;const epsg=32631;const xy=(x,y)=>{const p=run(`dgLcUtmInverse(${500000+x},${1000+y},${epsg})`);return[p.lon,p.lat];};const ring=(x0,y0,x1,y1)=>[xy(x0,y0),xy(x1,y0),xy(x1,y1),xy(x0,y1)];const outer=ring(0,0,20,10).map(p=>[p[1],p[0]]),hole=ring(1,1,3,3).map(p=>[p[1],p[0]]);ctx.PARK_POLY=[outer];ctx.PARK_HOLES=holes?[hole]:[];const park=run('dgSurfacePark(PARK_POLY,PARK_HOLES,32631)');ctx.park=park;const cells=[0,1].map(i=>({row:0,col:i,epsg,classKey:'green',areaM2:holes&&i===0?96:100,quadWgs:ring(i*10,0,(i+1)*10,10),center:{lat:xy(i*10+5,5)[1],lon:xy(i*10+5,5)[0]}}));ctx.cells=cells;ctx.geoms={};for(const c of cells)ctx.geoms['0:'+c.col]=ctx.window.DG_SURFACE_REVIEW.cell(c,park,epsg);run('DG_LC_LAST={result:{cells,groupAreas:{green:cells.reduce((n,c)=>n+c.areaM2,0),water:0,hard:0,bare:0,other:0}},report:{year:2021}};DG_SENS.geometry=geoms;DG_SENS.parkGeometry=park;DG_SENS.epsg=32631');return{ring,cells,park};}
test('fractional boundaries and overlaps conserve area; newest boundary takes precedence',()=>{const a=app(),f=fixture(a);a.ctx.features=[{type:'building',ring:f.ring(2,2,8,8)},{type:'pool',ring:f.ring(5,5,9,9)}];const result=a.run('dgSurfaceSummarize({green:200},cells,c=>c.classKey,geoms,features,32631,park)');assert.ok(Math.abs(result.building-27)<.001);assert.ok(Math.abs(result.pool-16)<.001);assert.ok(Math.abs(Object.values(result).reduce((s,v)=>s+v,0)-200)<.001);assert.equal(f.cells[0].classKey,'green');});
test('park holes and outside geometry are excluded from reviewed building area',()=>{const a=app(),f=fixture(a,true);a.ctx.features=[{type:'building',ring:f.ring(-20,-20,30,30)}];const r=a.run('dgSurfaceSummarize({green:196},cells,c=>c.classKey,geoms,features,32631,park)');assert.ok(Math.abs(r.building-196)<.001);assert.ok(Math.abs(r.green)<.001);});
test('self-crossing boundaries are rejected',()=>{const a=app();assert.equal(a.ctx.window.DG_SURFACE_REVIEW.validRing([[0,0],[1,1],[0,1],[1,0]]),false);assert.equal(a.ctx.window.DG_SURFACE_REVIEW.validRing([[0,0],[1,0],[1,1],[0,1]]),true);});
test('relative NDVI tiers need at least three observations and never relabel green raster cells',()=>{const a=app();const cells=Array.from({length:12},(_,i)=>({row:0,col:i,classKey:'green',rasterClassKey:'green',areaM2:100}));a.ctx.cells=cells;a.run('DG_LC_LAST={result:{cells}};DG_SENS.record.profile={cells:{}}');for(let i=0;i<cells.length;i++)a.run(`DG_SENS.record.profile.cells['0:${i}']={ndviMedianYear:${.2+i*.04},ndviObs:${i===11?2:4}}`);const result=a.run('dgSensVegetationTiers()');assert.equal(result.count,11);assert.equal(result.eligible,12);assert.equal(result.tiers.get('0:0'),'sparse');assert.equal(result.tiers.get('0:10'),'dense');assert.equal(result.tiers.has('0:11'),false);assert.ok(cells.every(c=>c.classKey==='green'));});
test('OSM basin and building-part outlines stay separate vector classes',()=>{const a=app(),f=fixture(a),coords=f.ring(2,2,8,8);coords.push(coords[0]);const ring=coords.map(([lon,lat])=>({lat,lon}));const objects=a.ctx.window.DG_SURFACE_REVIEW.objects([{type:'way',id:1,tags:{landuse:'basin'},geometry:ring},{type:'way',id:2,tags:{'building:part':'yes'},geometry:ring}],32631);assert.deepEqual(JSON.parse(JSON.stringify(objects.map(x=>x.type))),['water','building']);assert.ok(objects.every(x=>x.geometry.type==='MultiPolygon'));});
test('OSM multipolygon water retains its inner hole when converted to a vector feature',()=>{const a=app(),f=fixture(a);const outer=f.ring(2,2,8,8).map(([lon,lat])=>[lat,lon]),inner=f.ring(4,4,6,6).map(([lon,lat])=>[lat,lon]);a.ctx.extractRings=()=>({outer:[outer],inner:[inner]});a.ctx.objects=a.ctx.window.DG_SURFACE_REVIEW.objects([{type:'relation',id:77,tags:{type:'multipolygon',natural:'water'},members:[]}],32631);assert.equal(a.ctx.objects.length,1);assert.equal(a.ctx.objects[0].type,'water');assert.equal(a.ctx.objects[0].geometry.coordinates[0].length,2);a.ctx.geom=a.run('dgSurfaceFeatureGeometry(objects[0],32631)');assert.ok(Math.abs(a.run('dgSurfaceArea(geom)')-32)<.02);});
test('geometry fingerprint changes when the boundary or source classes change',async()=>{const a=app(),f=fixture(a);const R=a.ctx.window.DG_SURFACE_REVIEW;const first=await R.fingerprint(f.cells,a.ctx.PARK_POLY,[],{year:2021});assert.match(first,/^[a-f0-9]{64}$/);assert.equal(first,await R.fingerprint(f.cells,a.ctx.PARK_POLY,[],{year:2021}));const changed=structuredClone(f.cells);changed[0].classKey='water';assert.notEqual(first,await R.fingerprint(changed,a.ctx.PARK_POLY,[],{year:2021}));});
test('zero sensitivity stays zero and starts an unsaved preview',()=>{const a=app();a.run('dgSensSlide("hard",0)');assert.equal(a.run('DG_SENS.record.sens.hard'),0);assert.equal(a.run('DG_SENS.editing'),true);assert.equal(a.run('DG_SENS.record.draftDirty'),true);a.run('clearTimeout(DG_SENS.debounce)');});
test('new analyses show optional OSM evidence by default while saved opt-outs remain respected',async()=>{const a=app();assert.equal(a.run('dgSensNewRecord().useObjects'),true);const saved={...a.run('dgSensNewRecord()'),useObjects:false};a.ctx.window.DG_LC_VALIDATE.loadCampaigns=async()=>[saved];a.ctx.window.DG_SURFACE_REVIEW.fingerprint=async()=>'';const loaded=await a.run('dgSensLoadRecord()');assert.equal(loaded.useObjects,false);});
test('reopening a park analysis resets only the scan controls, never accepted results or manual edits',()=>{const a=app();const accepted={areas:{green:100,hard:100},features:[{properties:{class:'green'}}]},brush={type:'green',method:'visual-boundary'},rec={sens:{green:5,water:15,hard:95,bare:85},spectralEnabled:true,profile:{cells:{x:{obs:3}}},acceptedResult:accepted,features:[brush],corrections:{'0:1':{to:'water',method:'visual-cell'}}};a.ctx.rec=rec;a.run('dgSensResetScanState(rec)');assert.deepEqual(JSON.parse(JSON.stringify(rec.sens)),{green:50,water:50,hard:50,bare:50});assert.equal(rec.profile,null);assert.equal(rec.spectralEnabled,false);assert.equal(rec.acceptedResult,accepted);assert.equal(rec.features[0],brush);assert.equal(rec.corrections['0:1'].to,'water');});
test('saved spectral decisions are frozen until editing; visual decisions remain protected',()=>{const a=app();fixture(a);a.run('DG_SENS.record.corrections={"0:0":{from:"green",to:"water",method:"sensitivity"}};DG_SENS.editing=false');assert.equal(a.run('dgSensEffective(cells[0])'),'water');a.run('DG_SENS.editing=true');assert.equal(a.run('dgSensEffective(cells[0])'),'green');a.run('DG_SENS.record.corrections["0:0"].method="visual-cell"');assert.equal(a.run('dgSensEffective(cells[0])'),'water');});
test('inadequate or edge spectral evidence preserves the original class',()=>{const a=app();fixture(a);a.run('DG_SENS.record.profile={cells:{"0:0":{obs:1,ndvi:-.2,mndwi:.8,ndbi:-.4}}}');assert.equal(a.run('dgSensEffective(cells[0])'),'green');a.run('cells[0].areaM2=30;DG_SENS.record.profile.cells["0:0"].obs=5');assert.equal(a.run('dgSensEffective(cells[0])'),'green');});
test('PB04 offset and STAC scale-offset yield equivalent reflectance',()=>{const a=app();const fn=a.ctx.dgS2Reflectance;assert.equal(fn(3000,{properties:{'s2:processing_baseline':'05.11'}},'B04'),.2);assert.equal(fn(2000,{properties:{'s2:processing_baseline':'03.00'}},'B04'),.2);assert.ok(Math.abs(fn(3000,{assets:{B04:{'raster:bands':[{scale:.0001,offset:-.1}]}}},'B04')-.2)<1e-9);assert.equal(fn(0,{},'B04'),null);});
test('latest acquisitions use a rolling window ending today without future dates',()=>{const a=app();const range=a.ctx.dgS2SeasonRange(2021,'latest');assert.ok(Date.parse(range.end)<=Date.now());assert.ok(Math.abs((Date.parse(range.end)-Date.parse(range.start))/86400000-120)<1e-6);assert.match(range.label,/güncel/);});
test('account save uses revision compare-and-swap and reports conflicts',async()=>{const a=app();let filters=[];const q={eq:(k,v)=>{filters.push([k,v]);return q;},select:()=>q,maybeSingle:async()=>({data:null,error:null})};a.ctx.sb={from:()=>({update:()=>q})};await assert.rejects(()=>a.ctx.window.DG_SURFACE_REVIEW.save({owner:'u',parkId:7,fingerprint:'f'},4),/başka cihaz/);assert.ok(filters.some(([k,v])=>k==='revision'&&v===4));});
test('failed account save retains draft and never announces saved success',async()=>{const a=app();fixture(a);a.run('DG_SENS.record.features=[{type:"building",ring:cells[0].quadWgs}];dgSensRender=()=>{};dgSensRefreshLayer=()=>{}');a.ctx.window.DG_SURFACE_REVIEW.save=async()=>{throw Error('offline');};a.ctx.window.DG_LC_VALIDATE.saveCampaign=async()=>true;await a.run('dgSensAccept()');assert.equal(a.run('DG_SENS.record.acceptedAt'),undefined);assert.match(a.run('DG_SENS.status'),/Hesaba kaydedilemedi/);assert.equal(a.ctx.messages.at(-1)[1],'err');});
test('successful account save snapshots areas and freezes the accepted layer',async()=>{const a=app();fixture(a);a.run('DG_SENS.record.fingerprint="f";DG_SENS.record.features=[{type:"building",ring:cells[0].quadWgs}];dgSensRender=()=>{};dgSensRefreshLayer=()=>{}');a.ctx.window.DG_SURFACE_REVIEW.save=async()=>3;a.ctx.window.DG_LC_VALIDATE.saveCampaign=async()=>true;await a.run('dgSensAccept()');assert.equal(a.run('DG_SENS.revision'),3);assert.equal(a.run('DG_SENS.editing'),false);assert.equal(a.run('DG_SENS.record.draftDirty'),false);assert.ok(Math.abs(a.run('DG_SENS.record.acceptedAreas.building')-100)<.001);});
test('legacy spectral thresholds cannot relabel the single raster baseline',()=>{const a=app();fixture(a);a.run('DG_SENS.record.profile={cells:{"0:0":{obs:5,ndvi:.25,mndwi:-.15,ndbi:-.1}}};DG_SENS.record.sens.hard=100');assert.equal(a.run('dgSensEffective(cells[0])'),'green');assert.equal(a.run('dgSensAreas().hard'),0);assert.equal(a.run('DG_LC_LAST.result.groupAreas.green'),200);});
test('active park identity comes from DG_PARK, never the session cache Map',()=>{const a=app();assert.equal(a.run('dgSensParkId().id'),7);a.ctx.DG_PARK=null;assert.equal(a.run('dgSensParkId().id'),null);});
test('building cell correction remains a separate class and enters the accepted publication geometry',async()=>{const a=app();fixture(a);a.run('DG_SENS.record.fingerprint="f";DG_SENS.record.corrections={"0:0":{from:"green",to:"building",method:"visual-cell"}};dgSensRender=()=>{};dgSensRefreshLayer=()=>{}');a.ctx.window.DG_SURFACE_REVIEW.save=async()=>1;a.ctx.window.DG_LC_VALIDATE.saveCampaign=async()=>true;await a.run('dgSensAccept()');const snap=a.run('DG_SENS.record.acceptedResult');assert.equal(snap.areas.building,100);assert.equal(snap.areas.hard,0);assert.equal(snap.features.find(f=>f.properties.class==='building').properties.area_m2,100);});
test('OSM building footprint and pool stay independent, manual boundary overrides exact overlap',()=>{const a=app(),f=fixture(a);const way=(id,tags,ring)=>({type:'way',id,tags,geometry:[...ring,ring[0]].map(p=>({lon:p[0],lat:p[1]}))});const objs=a.ctx.dgSurfaceObjects([way(1,{building:'yes'},f.ring(0,0,10,10)),way(2,{leisure:'swimming_pool'},f.ring(10,0,20,10))],32631);a.ctx.objects=objs;a.run('DG_SENS.record.objectFeatures=objects;DG_SENS.record.useObjects=true');let area=a.run('dgSensAreas()');assert.ok(Math.abs(area.building-100)<.001);assert.ok(Math.abs(area.pool-100)<.001);assert.equal(area.hard,0);a.ctx.manual={type:'green',ring:f.ring(0,0,5,10)};a.run('DG_SENS.record.features=[manual]');area=a.run('dgSensAreas()');assert.ok(Math.abs(area.building-50)<.001);assert.ok(Math.abs(area.green-50)<.001);});
test('raw raster class prevents whole-cell road refinements spilling beyond exact vector boundary',()=>{const a=app();fixture(a);a.run('cells[0].classKey="hard";cells[0].rasterClassKey="green"');assert.equal(a.run('dgSensEffective(cells[0])'),'green');});
test('published surface snapshot rejects inconsistent area totals and other park identities',async()=>{const {reviewedSurface}=await import('../scripts/surface-report.mjs');const a=app();fixture(a);const snap=await a.run('dgSensResultSnapshot({...DG_SENS.record,acceptedAt:new Date().toISOString(),acceptedAreas:dgSensAreas()})');assert.equal(reviewedSurface(snap,7).classes.find(c=>c.key==='green').ha,.02);assert.throws(()=>reviewedSurface(snap,8),/kimliği/);const bad=structuredClone(snap);bad.areas.green=500;assert.throws(()=>reviewedSurface(bad,7),/uyuşmuyor/);});
test('slider changes reuse partitions without clipping and geometry edits invalidate the cache',()=>{const a=app(),f=fixture(a);a.ctx.features=[{type:'building',ring:f.ring(2,2,8,8)}];const first=a.run('dgSurfaceResolved(cells,c=>"green",geoms,features,32631,park)');const pc=a.ctx.window.polygonClipping;const original=pc.intersection;let calls=0;pc.intersection=(...args)=>{calls++;return original(...args);};try{const second=a.run('dgSurfaceResolved(cells,c=>"hard",geoms,features,32631,park)');assert.equal(calls,0);assert.equal(second[0].geom,first[0].geom);assert.ok(second.some(p=>p.type==='hard'));a.ctx.features.push({type:'pool',ring:f.ring(11,1,14,4)});const third=a.run('dgSurfaceResolved(cells,c=>"hard",geoms,features,32631,park)');assert.ok(calls>0);assert.ok(third.some(p=>p.type==='pool'));}finally{pc.intersection=original;}});
test('closing a park during snapshot preparation prevents its remote save',async()=>{const a=app();fixture(a);a.run('DG_SENS.record.features=[{type:"building",ring:cells[0].quadWgs}];dgSensRender=()=>{};dgSensRefreshLayer=()=>{};dgSensResultSnapshot=async()=>{DG_SENS.epoch++;return {}}');let saves=0;a.ctx.window.DG_SURFACE_REVIEW.save=async()=>{saves++;};await a.run('dgSensAccept()');assert.equal(saves,0);});
test('incomplete raster coverage cannot be saved as a complete publication map',async()=>{const a=app();fixture(a);a.run('DG_LC_LAST.result.groupAreas.green=300;DG_SENS.record.features=[{type:"building",ring:cells[0].quadWgs}];dgSensRender=()=>{};dgSensRefreshLayer=()=>{}');let saves=0;a.ctx.window.DG_SURFACE_REVIEW.save=async()=>{saves++;};await a.run('dgSensAccept()');assert.equal(saves,0);assert.match(a.run('DG_SENS.status'),/tüm parkı kapsamıyor/);});
test('plastic pier footprints override water completely without turning nearby water into hard surface',()=>{const a=app(),f=fixture(a);a.ctx.objects=[{type:'way',id:1,tags:{natural:'water'},geometry:[...f.ring(0,0,20,10),f.ring(0,0,20,10)[0]].map(p=>({lon:p[0],lat:p[1]}))},{type:'way',id:2,tags:{man_made:'pier',material:'plastic'},geometry:[...f.ring(2,2,8,8),f.ring(2,2,8,8)[0]].map(p=>({lon:p[0],lat:p[1]}))}];const out=a.run('dgSurfaceObjects(objects,32631)');a.ctx.features=out;const areas=a.run('dgSurfaceSummarize({green:200},cells,c=>c.classKey,geoms,features,32631,park)');assert.ok(Math.abs(areas.hard-36)<.001);assert.ok(Math.abs(areas.water-164)<.001);});
test('linear piers use an explicit width; unknown widths are not invented',()=>{const a=app(),f=fixture(a);const pts=[f.ring(2,2,2,2)[0],f.ring(8,2,2,2)[0]].map(p=>({lon:p[0],lat:p[1]}));a.ctx.objects=[{type:'way',id:1,tags:{man_made:'pier',width:'2'},geometry:pts},{type:'way',id:2,tags:{man_made:'pier'},geometry:pts}];assert.equal(a.run('dgSurfaceObjects(objects,32631).length'),1);});
test('closed paved highway ways remain lines unless OSM explicitly marks an area',()=>{const a=app(),f=fixture(a);const ring=f.ring(2,2,8,8),way=(id,tags)=>({type:'way',id,tags,geometry:[...ring,ring[0]].map(p=>({lon:p[0],lat:p[1]}))});a.ctx.objects=[way(1229015329,{highway:'cycleway',surface:'concrete'}),way(2,{highway:'pedestrian',surface:'paved',area:'yes'}),way(3,{highway:'pedestrian',surface:'paved','area:highway':'pedestrian'})];const out=a.run('dgSurfaceObjects(objects,32631)');assert.equal(out.length,2);assert.ok(out.every(o=>o.osmId!=='way/1229015329'));assert.ok(out.every(o=>a.run(`dgSurfaceArea(dgSurfaceFeatureGeometry(${JSON.stringify(o)},32631))`)>35));});
test('closed paved highway with explicit width is buffered as a route, not filled as a park-sized polygon',()=>{const a=app(),f=fixture(a);const ring=f.ring(2,2,8,8),way={type:'way',id:1,tags:{highway:'cycleway',surface:'concrete',width:'2'},geometry:[...ring,ring[0]].map(p=>({lon:p[0],lat:p[1]}))};a.ctx.objects=[way];const out=a.run('dgSurfaceObjects(objects,32631)');assert.equal(out.length,1);const area=a.run('dgSurfaceArea(dgSurfaceFeatureGeometry('+JSON.stringify(out[0])+',32631))');assert.ok(area>40&&area<100,`expected a buffered route near the 48 m perimeter, received ${area}`);});
test('legacy OSM masks are rebuilt while accepted report and manual edits remain intact',()=>{const a=app();const rec={objectVersion:'footprints-v2',objectFeatures:[{osmId:'way/old'}],features:[{type:'green',method:'visual-brush'}],corrections:{'1:2':{to:'water',method:'visual-cell'}},acceptedAt:'2026-01-01T00:00:00Z',acceptedResult:{areas:{green:100}},acceptedAreas:{green:100}};a.ctx.rec=rec;assert.equal(a.run('dgSensMigrateOsmObjects(rec)'),true);assert.equal(rec.objectFeatures,null);assert.equal(rec.objectVersion,null);assert.equal(rec.draftDirty,true);assert.deepEqual(rec.features,[{type:'green',method:'visual-brush'}]);assert.deepEqual(rec.corrections,{'1:2':{to:'water',method:'visual-cell'}});assert.equal(rec.acceptedResult.areas.green,100);assert.equal(a.run('dgSensMigrateOsmObjects(rec)'),false);});
test('live report follows edits while retaining original raster in a separate disclosure',()=>{const a=app();fixture(a);a.el('landCoverReport').innerHTML='original baseline';a.run('dgSensUpdateSummary()');assert.match(a.el('landCoverReport').innerHTML,/Güncel yüzey önizlemesi/);a.run('DG_SENS.record.corrections={"0:0":{to:"building",method:"visual-cell"}};dgSensUpdateSummary()');assert.match(a.el('landCoverReport').innerHTML,/Bina.*0.010 ha/);assert.match(a.el('landCoverReport').innerHTML,/original baseline/);assert.equal((a.el('landCoverReport').innerHTML.match(/<details\b/g)||[]).length,1);});
test('opacity extremes and display corner rounding preserve analytic geometry and areas',()=>{const a=app();fixture(a);const before=a.run('JSON.stringify(dgSensAreas())');a.run('dgSensOpacity(0)');assert.equal(a.run('DG_SENS.opacity'),0);a.run('dgSensOpacity(100)');assert.equal(a.run('DG_SENS.opacity'),100);const softened=a.run('dgSensSoftRing([...cells[0].quadWgs,cells[0].quadWgs[0]],32631)');assert.ok(softened.length>5);assert.equal(a.run('JSON.stringify(dgSensAreas())'),before);});
test('exact display reuses analytical geometry, preserving measured buildings and all totals',()=>{
 const a=app();const shift=r=>r.map(p=>[p[0]+500000,p[1]+1000]);const c=shift([[40,0],[40,8],[48,8],[48,16],[56,16],[56,24],[64,24],[64,32],[72,32],[72,40],[80,40],[80,100]]),park=[[shift([[0,0],[100,0],[100,100],[0,100],[0,0]])]],building=[[shift([[10,10],[25,10],[25,25],[10,25],[10,10]])]],green=[[[[500000,1000],...c,[500000,1100],[500000,1000]]]],hard=[[[...c,[500100,1100],[500100,1000],c[0]]]];
 const g=polygonClipping.difference(green,building);a.ctx.visualPark=park;a.ctx.visualParts=[{type:'green',method:'review-cell',geom:g,areaM2:1},{type:'hard',method:'review-cell',geom:hard,areaM2:2},{type:'building',method:'osm-boundary',geom:building,areaM2:225}];const before=JSON.stringify(a.ctx.visualParts);const exact=a.run('dgSurfaceMergeSync(visualParts,32631)');a.ctx.exact=exact;const visual=a.run('dgSurfaceDisplaySync(visualParts,32631,visualPark,exact)');assert.equal(JSON.stringify(a.ctx.visualParts),before);assert.equal(visual,exact);assert.deepEqual(JSON.parse(JSON.stringify(visual.find(f=>f.properties.class==='building').geometry)),JSON.parse(JSON.stringify(exact.find(f=>f.properties.class==='building').geometry)));assert.deepEqual(visual.map(f=>f.properties.area_m2),exact.map(f=>f.properties.area_m2));
});

test('unmodified raster can be accepted without spectral scanning',async()=>{const a=app();fixture(a);a.run('dgSensRender=()=>{};dgSensRefreshLayer=()=>{}');a.ctx.window.DG_SURFACE_REVIEW.save=async()=>1;a.ctx.window.DG_LC_VALIDATE.saveCampaign=async()=>true;await a.run('dgSensAccept()');assert.equal(a.run('DG_SENS.record.acceptedAreas.green'),200);assert.equal(a.run('DG_SENS.record.profile'),null);});
test('raw view excludes manual cells, boundaries and OSM without deleting edits',()=>{const a=app(),f=fixture(a);a.ctx.manual={type:'building',ring:f.ring(0,0,10,10)};a.run('DG_SENS.record.features=[manual];DG_SENS.record.corrections={"0:1":{to:"hard",method:"visual-cell"}}');const before=a.run('JSON.stringify(DG_SENS.record)');assert.equal(a.run('dgSensAreas().hard'),100);a.run('DG_SENS.rawView=true;DG_SENS.visualVersion++');assert.equal(a.run('dgSensAreas().green'),200);assert.equal(a.run('JSON.stringify(DG_SENS.record)'),before);a.run('DG_SENS.rawView=false;DG_SENS.visualVersion++');assert.equal(a.run('dgSensAreas().hard'),100);});
test('brush paints each touched raster cell through the same decision path as a map tap',async()=>{const a=app();fixture(a);a.run('dgSensRepartition=async()=>{};dgSensSave=async()=>true');const point=(x,y)=>{const p=a.run(`dgLcUtmInverse(${500000+x},${1000+y},32631)`);return[p.lat,p.lon];};a.ctx.stroke=[point(5,5)];await a.run('dgSensBrushCommit(stroke,"hard",5)');assert.deepEqual(JSON.parse(JSON.stringify(Object.keys(a.run('DG_SENS.record.corrections')))),['0:0']);assert.equal(a.run('DG_SENS.record.corrections["0:0"].method'),'visual-cell');assert.equal(a.run('DG_SENS.record.corrections["0:0"].to'),'hard');assert.equal(a.run('DG_SENS.record.features.length'),0);assert.equal(a.run('dgSensAreas().hard'),100);assert.equal(a.ctx.cells[0].classKey,'green');a.run('dgSensBrushUndo()');assert.equal(a.run('dgSensAreas().green'),200);assert.deepEqual(JSON.parse(JSON.stringify(a.run('DG_SENS.record.corrections'))),{});});
test('brush across multiple cells is cell-aligned; undo restores only cells still owned by that stroke',async()=>{const a=app();fixture(a);a.run('dgSensRepartition=async()=>{};dgSensSave=async()=>true');const point=(x,y)=>{const p=a.run(`dgLcUtmInverse(${500000+x},${1000+y},32631)`);return[p.lat,p.lon];};a.ctx.stroke=[point(0,5),point(20,5)];await a.run('dgSensBrushCommit(stroke,"water",5)');assert.deepEqual(JSON.parse(JSON.stringify(Object.keys(a.run('DG_SENS.record.corrections')).sort())),['0:0','0:1']);assert.equal(a.run('dgSensAreas().water'),200);a.run('dgSensDecide("0:0","building")');a.run('dgSensBrushUndo()');assert.equal(a.run('dgSensAreas().building'),100);assert.equal(a.run('dgSensAreas().green'),100);assert.equal(a.run('dgSensAreas().water'),0);});
test('legacy continuous brush masks migrate to full grid-cell decisions and remain undoable',()=>{const a=app(),f=fixture(a);a.ctx.oldMask={type:'water',method:'visual-brush',ts:'2026-01-01T00:00:00Z',geometry:{type:'MultiPolygon',coordinates:[[[...f.ring(2,2,5,8),f.ring(2,2,5,8)[0]]]]}};a.run('DG_SENS.record.features=[oldMask];dgSensSave=()=>true');assert.equal(a.run('dgSensMigrateBrushMasks(DG_SENS.record,cells,geoms,park,32631)'),true);assert.equal(a.run('DG_SENS.record.features.length'),0);assert.equal(a.run('dgSensAreas().water'),100);assert.equal(a.run('DG_SENS.record.corrections["0:0"].method'),'visual-cell');a.run('dgSensBrushUndo()');assert.equal(a.run('dgSensAreas().water'),0);assert.equal(a.run('dgSensAreas().green'),200);});
test('brush outside the park or invalid stroke cannot add a correction',async()=>{const a=app();fixture(a);a.run('dgSensRepartition=async()=>{};dgSensSave=async()=>true');await a.run('dgSensBrushCommit([[80,80]],"hard",10)');await a.run('dgSensBrushCommit([[NaN,0]],"hard",10)');assert.equal(a.run('DG_SENS.record.features.length'),0);});

test('brush cell decisions and undo history survive draft/account reload; invalid geometry is rejected',async()=>{const a=app();fixture(a);a.run('dgSensRepartition=async()=>{};dgSensSave=async()=>true');a.ctx.stroke=a.run('cells.map(c=>[c.center.lat,c.center.lon])');await a.run('dgSensBrushCommit(stroke,"water",10)');const saved=a.run('JSON.parse(JSON.stringify(DG_SENS.record))');assert.equal(saved.features.length,0);assert.equal(Object.values(saved.corrections).length,2);assert.ok(Object.values(saved.corrections).every(d=>d.method==='visual-cell'));a.ctx.window.DG_LC_VALIDATE.loadCampaigns=async()=>[saved];a.ctx.window.DG_SURFACE_REVIEW.load=async()=>null;const loaded=await a.run('dgSensLoadRecord()');assert.deepEqual(JSON.parse(JSON.stringify(loaded.corrections)),JSON.parse(JSON.stringify(saved.corrections)));assert.deepEqual(JSON.parse(JSON.stringify(loaded.brushHistory)),JSON.parse(JSON.stringify(saved.brushHistory)));const bad={type:'water',method:'visual-boundary',geometry:{type:'MultiPolygon',coordinates:[[[[0,0],[1,0],[1,1],[0,1],[0,0]]]]}};bad.geometry.coordinates[0][0][0][0]=NaN;assert.equal(a.ctx.window.DG_SURFACE_REVIEW.validFeature(bad),false);});

test('scan and all four sensitivity sliders remain in the original themed controls',()=>{const a=app();fixture(a);a.run('dgSensRender()');const html=a.el('lcSens').innerHTML;assert.equal(a.run('dgSensNewRecord().period'),'latest');assert.match(html,/id="dgSensScanBtn"/);assert.match(html,/onclick="dgSensScan\(\)"/);for(const k of ['green','water','hard','bare'])assert.ok(html.includes('id="dgSensRange-'+k+'"'));const toolbar=a.el("surfaceBrushTools").innerHTML;assert.match(toolbar,/id="dgSensPeriod"/);assert.match(toolbar,/value="ytd"[\s\S]*?Güncel yıl/);assert.doesNotMatch(html,/id="dgSensBrushType"/);assert.match(readFileSync(new URL("../src/ui/lc-sens.js",import.meta.url),"utf8"),/id="dgSensBrushBtn"[\s\S]*?dgSensBrushToggle/);assert.match(toolbar,/id="dgSensBoundaryDetails"[\s\S]*?id="dgSensDrawType"/);assert.match(toolbar,/id="dgSensDataDetails"[\s\S]*?dg-editor-menu-body/);});
test('scan obtains a profile but does not automatically replace raw classes',async()=>{const a=app();fixture(a);let calls=0;a.ctx.window.DG_LC_S2.profile=async()=>{calls++;return{cells:{'0:0':{obs:5,ndvi:.25,mndwi:-.15,ndbi:-.1}},scenes:[],radiometryVersion:'pb04-offset-v1'};};a.run('dgSensRender=()=>{};dgSensRefreshLayer=()=>{};dgSensSave=async()=>true');await a.run('dgSensScan()');assert.equal(calls,1);assert.equal(a.run('dgSensEffective(cells[0])'),'green');assert.equal(a.run('dgSensAreas().green'),200);assert.ok(a.run('DG_SENS.record.profile'));});
test('each successful scan starts at neutral sensitivity and replaces the previous spectral profile',async()=>{const a=app();fixture(a);a.run('DG_SENS.record.sens={green:0,water:100,hard:0,bare:100};DG_SENS.record.spectralEnabled=true;DG_SENS.record.profile={cells:{old:{obs:5}}};dgSensRender=()=>{};dgSensRefreshLayer=()=>{};dgSensSave=async()=>true');a.ctx.window.DG_LC_S2.profile=async()=>({cells:{'0:0':{obs:5,ndvi:.2,mndwi:0,ndbi:0}},scenes:[],radiometryVersion:'pb04-offset-v1'});await a.run('dgSensScan()');assert.deepEqual(JSON.parse(JSON.stringify(a.run('DG_SENS.record.sens'))),{green:50,water:50,hard:50,bare:50});assert.equal(a.run('DG_SENS.record.spectralEnabled'),false);assert.equal(a.run('DG_SENS.record.profile.cells.old'),undefined);assert.equal(a.run('dgSensEffective(cells[0])'),'green');});
test('user changes a sensitivity slider after scanning; returning to neutral restores raster',()=>{const a=app();fixture(a);a.run('DG_SENS.record.profile={cells:{"0:0":{obs:5,ndvi:.25,mndwi:-.15,ndbi:-.1}}};dgSensSlide("hard",100);clearTimeout(DG_SENS.debounce);clearTimeout(DG_SENS.saveTimer)');assert.equal(a.run('dgSensEffective(cells[0])'),'hard');assert.equal(a.run('DG_LC_LAST.result.groupAreas.green'),200);a.run('dgSensSlide("hard",50);clearTimeout(DG_SENS.debounce);clearTimeout(DG_SENS.saveTimer)');assert.equal(a.run('dgSensEffective(cells[0])'),'green');});
test('sensitivity sliders cannot replace visual cell corrections or brush boundaries',async()=>{const a=app();fixture(a);a.run('DG_SENS.record.profile={cells:{"0:0":{obs:5,ndvi:.25,mndwi:-.15,ndbi:-.1}}};DG_SENS.record.corrections={"0:0":{to:"water",method:"visual-cell"}};dgSensSlide("hard",100);clearTimeout(DG_SENS.debounce);clearTimeout(DG_SENS.saveTimer)');assert.equal(a.run('dgSensEffective(cells[0])'),'water');a.run('dgSensRepartition=async()=>{};dgSensSave=async()=>true');a.ctx.stroke=a.run('cells.map(c=>[c.center.lat,c.center.lon])');await a.run('dgSensBrushCommit(stroke,"building",10)');assert.ok(a.run('dgSensAreas().building')>0);assert.equal(a.run('DG_LC_LAST.result.groupAreas.green'),200);});
test('failed scan clears its old profile and starts neutral; a late scan cannot replace the next park',async()=>{const a=app();fixture(a);a.run('DG_SENS.record.sens={green:0,water:0,hard:100,bare:0};DG_SENS.record.spectralEnabled=true;DG_SENS.record.profile={cells:{old:{obs:4}}};dgSensRender=()=>{};dgSensRefreshLayer=()=>{};dgSensSave=async()=>true');a.ctx.window.DG_LC_S2.profile=async()=>{throw Error('network failure');};await a.run('dgSensScan()');assert.equal(a.run('DG_SENS.record.profile'),null);assert.deepEqual(JSON.parse(JSON.stringify(a.run('DG_SENS.record.sens'))),{green:50,water:50,hard:50,bare:50});assert.equal(a.run('DG_SENS.record.spectralEnabled'),false);assert.match(a.run('DG_SENS.status'),/Tarama başarısız/);a.ctx.window.DG_LC_S2.profile=async()=>{a.run('DG_SENS.epoch++');return{cells:{}};};await a.run('dgSensScan()');assert.equal(a.run('DG_SENS.record.profile'),null);});

test('raw view menu keeps return enabled while editing tools remain disabled',()=>{
 const a=app();fixture(a);a.run('DG_SENS.rawView=true;dgSensRenderPaintTools()');
 const html=a.el('surfaceBrushTools').innerHTML;
 const toggle=html.match(/<button[^>]*onclick="dgSensRawView\(!DG_SENS.rawView\)"[^>]*>/)?.[0];
 assert.ok(toggle);assert.doesNotMatch(toggle,/disabled/);
 assert.match(html,/<select id="dgSensBrushType"[^>]*disabled/);
 a.run('DG_SENS.busy=true;dgSensRenderPaintTools()');
 assert.match(a.el('surfaceBrushTools').innerHTML,/<button[^>]*onclick="dgSensRawView\(!DG_SENS.rawView\)"[^>]*disabled/);
});
test('raw-to-edit round trip reuses prepared editing geometry and preserves corrections',async()=>{
 const a=app();fixture(a);a.run('DG_SENS.record.corrections={"0:0":{to:"water",method:"visual-cell"}}');
 const original=a.run('DG_SENS.geometry'),before=a.run('JSON.stringify(DG_SENS.record)');
 let partitions=0;a.ctx.dgSensRepartition=async()=>{partitions++;a.run('DG_SENS.geometry={raw:true};DG_SENS.partitionVersion=123');};
 a.run('dgSensDrawCancel=()=>{};dgSensRender=()=>{};dgSensRefreshLayer=async()=>{};dgSensUpdateSummary=()=>{}');
 await a.run('dgSensRawView(true)');assert.equal(a.run('DG_SENS.rawView'),true);
 await a.run('dgSensRawView(false)');assert.equal(a.run('DG_SENS.rawView'),false);
 assert.equal(a.run('DG_SENS.geometry'),original);assert.equal(partitions,1);
 assert.equal(a.run('dgSensAreas().water'),100);assert.equal(a.run('JSON.stringify(DG_SENS.record)'),before);
 assert.equal(a.run('DG_SENS.busy'),false);assert.equal(a.run('DG_SENS.editView'),null);
 await a.run('dgSensRawView(false)');assert.equal(partitions,1);
});
test('real raw preparation excludes boundaries, then restores manual and accepted data',async()=>{
 const a=app(),f=fixture(a);a.ctx.boundary={type:'building',ring:f.ring(0,0,10,10)};
 a.run('DG_SENS.record.objectFeatures=[];DG_SENS.record.features=[boundary];DG_SENS.record.corrections={"0:1":{to:"water",method:"visual-cell"}};DG_SENS.record.acceptedResult={areas:{building:100,water:100}};dgSensDrawCancel=()=>{};dgSensRender=()=>{};dgSensRefreshLayer=async()=>{};dgSensUpdateSummary=()=>{}');
 const before=a.run('JSON.stringify(DG_SENS.record)'),editing=a.run('JSON.stringify(dgSensAreas())');
 await a.run('dgSensRawView(true)');assert.equal(a.run('dgSensAreas().green'),200);assert.equal(a.run('dgSensAreas().building'),0);
 await a.run('dgSensRawView(false)');assert.equal(a.run('JSON.stringify(dgSensAreas())'),editing);assert.equal(a.run('JSON.stringify(DG_SENS.record)'),before);
});

test('OSM object picker returns an exact pier footprint and rejects distant taps',()=>{
 const a=app(),f=fixture(a);const ring=f.ring(2,2,8,8),geometry=[...ring,ring[0]].map(p=>({lat:p[1],lon:p[0]}));
 a.ctx.elements=[{type:'way',id:77,tags:{man_made:'pier',area:'yes'},geometry}];
 const center=a.run('dgLcUtmInverse(500005,1005,32631)');a.ctx.latlng={lat:center.lat,lng:center.lon};
 const picked=a.run('dgSensFindObjectAt(latlng,elements)');a.ctx.picked=picked;assert.equal(picked.type,'hard');assert.equal(picked.osmId,'way/77');assert.ok(Math.abs(a.run('dgSurfaceArea(dgSurfaceFeatureGeometry(picked,32631))')-36)<.01);
 const far=a.run('dgLcUtmInverse(500019,1009,32631)');a.ctx.latlng={lat:far.lat,lng:far.lon};assert.equal(a.run('dgSensFindObjectAt(latlng,elements)'),null);
});
test('OSM selected class stays authoritative and changes reviewed area on apply',async()=>{
 const a=app(),f=fixture(a);a.run('DG_SENS.parkGeometry=park;dgSensRepartition=async()=>{DG_SENS.geometry=geoms;DG_SENS.parkGeometry=park};dgSensSave=async()=>true');
 const boundary=f.ring(2,2,8,8);boundary.push([...boundary[0]]);a.ctx.selection={type:'hard',osmId:'way/77',geometry:{type:'MultiPolygon',coordinates:[[boundary]]}};
 a.run('DG_SENS.drawType="hard";DG_SENS.objectPreview=selection;DG_SENS.record.corrections={"0:0":{to:"water",method:"visual-cell"}};dgSensSetDrawType("water")');
 a.el('dgSensDrawType').value='building';
 assert.equal(a.run('DG_SENS.record.features.length'),0);
 await a.run('dgSensObjectApply()');
 assert.equal(a.run('DG_SENS.record.features[0].source'),'osm-selected');assert.equal(a.run('DG_SENS.record.features[0].type'),'water');
 assert.equal(a.run('DG_SENS.record.corrections["0:0"].to'),'water');assert.equal(a.run('DG_SENS.objectPreview'),null);
 const areas=a.run('dgSurfaceSummarize({green:200,water:0,hard:0,bare:0,other:0},cells,c=>c.classKey,geoms,dgSensFeatures(),32631,park)');
 assert.ok(Math.abs(areas.water-36)<.01);assert.ok(Math.abs(areas.green-164)<.01);
 assert.match(a.run('DG_SENS.status'),/36/);
});


test('missing surface geometry makes review parts empty and safe',()=>{const a=app(),f=fixture(a);assert.deepEqual(JSON.parse(JSON.stringify(a.ctx.window.DG_SURFACE_REVIEW.resolved(f.cells,c=>c.classKey,null,[],32631,f.park))),[]);let calls=0;a.ctx.window.DG_SURFACE_REVIEW.resolved=()=>{calls++;throw Error('must not resolve missing geometry');};a.run('DG_SENS.geometry=null');assert.deepEqual(JSON.parse(JSON.stringify(a.run('dgSensParts()'))),[]);assert.equal(calls,0);assert.equal(a.run('DG_SENS.partsMemo'),null);});
test('surface clipping removes millimetre-collapsed vertices before sweep-line processing',()=>{const a=app();fixture(a);const pc=a.ctx.window.polygonClipping,intersection=pc.intersection;let sanitized=false;pc.intersection=(left,right)=>{sanitized=left[0][0].length===5;return intersection(left,right);};a.ctx.noisy=[[[500000,1000],[500010,1000],[500010,1010],[500010.0001,1010],[500000,1010],[500000,1000]]];a.ctx.clipped=a.run('dgSurfaceClip("intersection",[noisy],DG_SENS.parkGeometry)');assert.equal(sanitized,true);assert.ok(Math.abs(a.run('dgSurfaceArea(clipped)')-100)<.001);});
test('sweep-line topology failures become a contained boundary error',()=>{const a=app();fixture(a);const pc=a.ctx.window.polygonClipping,intersection=pc.intersection;pc.intersection=()=>{throw Error('Unable to find segment #2005777 in SweepLine tree.');};assert.throws(()=>a.run('dgSurfaceClip("intersection",DG_SENS.parkGeometry,DG_SENS.parkGeometry)'),/çakışan veya bozuk köşe/);pc.intersection=intersection;});
test('stale and busy surface layers cannot handle current map clicks',()=>{const a=app();fixture(a);const state=a.run('({epoch:DG_SENS.epoch,geometry:DG_SENS.geometry})');assert.equal(a.run(`dgSensLayerClickIsCurrent(${state.epoch},DG_SENS.geometry)`),true);a.run('DG_SENS.busy=true');assert.equal(a.run(`dgSensLayerClickIsCurrent(${state.epoch},DG_SENS.geometry)`),false);a.run('DG_SENS.busy=false;DG_SENS.epoch++');assert.equal(a.run(`dgSensLayerClickIsCurrent(${state.epoch},DG_SENS.geometry)`),false);a.run('DG_SENS.epoch--;DG_SENS.geometry=null');assert.equal(a.run(`dgSensLayerClickIsCurrent(${state.epoch},null)`),false);});
