import { readFileSync } from 'node:fs';
import vm from 'node:vm';
const ROOT=process.cwd();
const fix=JSON.parse(readFileSync(ROOT+'/test/fixtures/goksu-park.json','utf8'));
const ring=fix.ring;
const ctx={console,fetch,setTimeout,clearTimeout,URL,URLSearchParams,Map,Set,Math,JSON,Date,Number,Array,Object,String,Boolean,Promise,RegExp,Error,Intl,isNaN,parseInt,parseFloat,ArrayBuffer,Uint8Array,Uint16Array,Int32Array,Float32Array,Float64Array,DataView,TextDecoder,TextEncoder,AbortController,Response,Headers,Request,Buffer,window:null,self:null};
ctx.Worker=class{constructor(u){this.u=u}postMessage(){throw new Error('worker')}terminate(){}addEventListener(){}};
ctx.URL.createObjectURL=()=>'blob:x';ctx.Blob=class{};
ctx.window=ctx;ctx.self=ctx;vm.createContext(ctx);
vm.runInContext(readFileSync(ROOT+'/vendor/geotiff-2.1.3.js','utf8'),ctx,{filename:'geotiff.js'});
console.log('geotiff yuklendi, GeoTIFF tip:', typeof ctx.GeoTIFF);
