/* Public bibliographic data only. Never used for permissions or numeric inputs. */
(function(root){
 const fields={author_name:120,institution:180,department:180,program:120,advisor:180,orcid:19,project_name:240,title:300,purpose:1600,study_type:60,funding:300,sampling:1600,instruments:1000,start_date:10,end_date:10};
 function normalizeOrcid(value){const v=String(value||'').trim().replace(/^https?:\/\/orcid\.org\//i,'').replace(/[\s-]/g,'').toUpperCase();return /^\d{15}[\dX]$/.test(v)?v.match(/.{4}/g).join('-'):String(value||'').trim();}
 function clean(input){const out={};for(const[k,max]of Object.entries(fields)){const v=input?.[k];out[k]=typeof v==='string'?(k==='orcid'?normalizeOrcid(v):v).replace(/[\u0000-\u001f\u007f]/g,' ').trim().slice(0,max):'';}out.independent=input?.independent===true;return out;}
 function orcidValid(value){if(!value)return true;if(!/^\d{4}-\d{4}-\d{4}-\d{3}[\dX]$/.test(value))return false;const s=value.replace(/-/g,''),check=(12-[...s.slice(0,15)].reduce((a,c)=>(a+Number(c))*2,0)%11)%11;return s.at(-1)===(check===10?'X':String(check));}
 function validate(input){const v=clean(input),errors={};for(const[k,label]of Object.entries({author_name:'Yazar adı ve soyadı',project_name:'Proje adı',title:'Rapor başlığı',purpose:'Çalışmanın amacı'}))if(!v[k])errors[k]=label+' gereklidir.';if(v.purpose&&v.purpose.length<20)errors.purpose='Çalışmanın amacını en az 20 karakterle açıklayın.';for(const k of ['start_date','end_date'])if(v[k]&&(!/^\d{4}-\d{2}-\d{2}$/.test(v[k])||!Number.isFinite(Date.parse(v[k]))||new Date(v[k]).toISOString().slice(0,10)!==v[k]))errors[k]='Geçerli saha tarihi girin.';if(v.start_date&&v.end_date&&(v.end_date<v.start_date||v.end_date>new Date().toISOString().slice(0,10)))errors.end_date='Saha tarih aralığı geçersiz.';if(!orcidValid(v.orcid))errors.orcid='ORCID kimliğinin biçimini ve kontrol basamağını denetleyin.';return{value:v,errors,valid:!Object.keys(errors).length};}
 function decode(note){try{const x=typeof note==='string'?JSON.parse(note):note;if(x?.schema!=='dendrogeo-report-context/1')return null;const v=validate(x.study);if(!v.valid)throw Error('Yayın künyesi geçersiz: '+Object.values(v.errors).join(' '));if(x.publication_consent!==true)throw Error('Yayın künyesi için paylaşım onayı eksik.');return v.value;}catch(e){if(/Yayın künyesi/.test(e.message))throw e;return null;}}
 root.DG_REPORT_CONTEXT_DOMAIN={fields,clean,validate,orcidValid,normalizeOrcid,decode};
})(globalThis);
